'use client';
import {useEffect,useRef,useState} from 'react';
import Workspace from './workspace';
import MembersPanel from './members-panel';
import EmployeeWorkspace from './employee-workspace';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel,AlertDialogAction,AlertDialogFooter} from '@/components/ui/alert-dialog';
import {Building2,Plus,Pencil,Package} from 'lucide-react';
type Company={id:string;name:string;role:string};
export default function CompanyPortal({email}:{email:string}){
const [companies,setCompanies]=useState<Company[]>([]),[active,setActive]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[form,setForm]=useState<'create'|'rename'|null>(null),[name,setName]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[pending,setPending]=useState('');
const createId=useRef(''),saving=useRef(false);
const preference='pantry-company:'+email;
async function load(){setLoading(true);setError('');try{const r=await fetch('/api/companies'),d=await r.json() as {companies:Company[];error?:string};if(!r.ok)throw new Error(d.error);setCompanies(d.companies);let saved=new URLSearchParams(location.search).get('company')||'';if(!saved)try{saved=localStorage.getItem(preference)||'';}catch{}setActive(d.companies.find(c=>c.id===saved)?.id||d.companies[0]?.id||'');if(!d.companies.length){setForm('create');createId.current=crypto.randomUUID();}}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
useEffect(()=>{void load();},[]);
useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
function switchCompany(id:string){setActive(id);setDirty(false);setPending('');try{localStorage.setItem(preference,id);}catch{}}
function openCreate(){createId.current=crypto.randomUUID();setName('');setError('');setForm('create');}
async function save(e:React.FormEvent){e.preventDefault();if(saving.current)return;saving.current=true;setBusy(true);setError('');try{const r=await fetch('/api/companies',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:form,id:form==='create'?createId.current:active,name})});const d=await r.json() as {company:Company;error?:string};if(!r.ok)throw new Error(d.error);setCompanies(c=>[...c.filter(x=>x.id!==d.company.id),d.company]);if(form==='create'&&dirty)setPending(d.company.id);else switchCompany(d.company.id);setForm(null);}catch(e){setError((e as Error).message);}finally{saving.current=false;setBusy(false);}}
const current=companies.find(c=>c.id===active);
return <><div className="company-bar"><div className="company-control"><Building2 size={19}/><label htmlFor="company-switch">Company</label><Select value={active} disabled={loading||busy} onValueChange={id=>{if(id!==active){if(dirty)setPending(id);else switchCompany(id);}}}><SelectTrigger id="company-switch" className="company-select"><SelectValue placeholder="Choose a company"/></SelectTrigger><SelectContent>{companies.map(c=><SelectItem value={c.id} key={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></div><div className="company-actions">{current?.role==='owner'&&<Button variant="ghost" disabled={busy} onClick={()=>{setName(current.name);setError('');setForm('rename');}}><Pencil size={15}/>Rename</Button>}<Button variant="outline" disabled={loading||busy} onClick={openCreate}><Plus size={16}/>New company</Button></div></div>
{loading?<div className="empty" role="status">Loading your companies…</div>:current?<><details className="membership-details"><summary>Members & ownership</summary><MembersPanel key={active} companyId={active} owner={current.role==='owner'}/></details>{current.role==='employee'?<EmployeeWorkspace companyId={active}/>:<Workspace key={active} email={email} companyId={active} companyName={current.name} role={current.role} onDirtyChange={setDirty}/>}</>:<main><div className="empty"><Package size={35}/><h1>Welcome to Pantrack.</h1><p>Create your company's workspace to start saving products and preparing orders.</p><Button onClick={openCreate}>Create company</Button><p>Signed in as {email}</p><a href="/auth/signout" target="_top">Sign out</a></div></main>}
{error&&!form&&<div className="error" role="alert">{error}<Button variant="ghost" onClick={()=>void load()}>Retry</Button></div>}
<Dialog open={!!form} onOpenChange={open=>{if(!open&&!busy)setForm(null);}}><DialogContent className="order-dialog"><DialogTitle>{form==='create'?'Create a company workspace':'Rename company'}</DialogTitle><DialogDescription>{form==='create'?'This company gets its own catalog and order history. Only your signed-in account has access.':'Your saved products and orders stay with this company.'}</DialogDescription><form className="product-form" onSubmit={save}><label>Company name<Input autoFocus required maxLength={100} placeholder="e.g. Astoria Coffee House" value={name} onChange={e=>setName(e.target.value)}/></label>{form==='create'&&<p>Includes 12 clearly labeled sample products to try the ordering workflow.</p>}{error&&<p role="alert" className="error">{error}</p>}<Button type="submit" disabled={busy||!name.trim()}>{busy?'Saving…':form==='create'?'Create company':'Save name'}</Button></form></DialogContent></Dialog>
<AlertDialog open={!!pending} onOpenChange={open=>!open&&setPending('')}><AlertDialogContent><AlertDialogTitle>Switch company?</AlertDialogTitle><AlertDialogDescription>Your unfinished order quantities will be cleared. Saved products and orders will remain in the current company.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Stay here</AlertDialogCancel><AlertDialogAction onClick={()=>switchCompany(pending)}>Switch company</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
</>;
}
