'use client';
import {useEffect,useState} from 'react';
import MenuWasteRecorder from './menu-waste-recorder';
import {useWorkspaceTheme} from './workspace-theme';
import {Button} from '@/components/ui/button';
import {Moon,Sun,Trash2} from 'lucide-react';
export default function EmployeeWorkspace({companyId,email,onDirtyChange}:{companyId:string;email:string;onDirtyChange:(dirty:boolean)=>void}){
  const [refresh,setRefresh]=useState(0),[page,setPage]=useState<'inventory'|'waste'>('inventory'),[wasteEnabled,setWasteEnabled]=useState(false),[wasteLaunch,setWasteLaunch]=useState(0);
  const {theme,toggleTheme}=useWorkspaceTheme();
  const [data,setData]=useState<{products:{id:string;name:string;pack:string}[];records:{productId:string;onHand:number;settings:{unit:string}}[];recipes:{id:string;name:string;ingredients:{productId:string;quantity:number;unit:string}[]}[];events:{state:string;occurredAt:string}[]}|null>(null),[error,setError]=useState('');
  useEffect(()=>{let live=true;async function load(){try{const values=await Promise.all(['workspace','inventory','sales','sales/events'].map(async name=>{const r=await fetch('/api/'+name+'?companyId='+encodeURIComponent(companyId));const d=await r.json() as NonNullable<typeof data> & {error?:string};if(!r.ok)throw new Error(d.error);return d;}));if(live)setData({products:values[0].products,records:values[1].records,recipes:values[2].recipes,events:values[3].events||[]});}catch(e){if(live)setError((e as Error).message);}}void load();return()=>{live=false;};},[companyId,refresh]);
  return <main className="employee-workspace" data-workspace-theme={theme}><nav className="employee-section-nav" aria-label="Workspace sections"><Button variant="outline" aria-current={page==='inventory'?'page':undefined} onClick={()=>setPage('inventory')}>Inventory</Button>{wasteEnabled&&<Button variant="outline" aria-current={page==='waste'?'page':undefined} onClick={()=>setPage('waste')}>Waste</Button>}</nav><div className="employee-waste-actions"><Button className="waste-entry-button" variant="outline" disabled={!wasteEnabled} onClick={()=>setWasteLaunch(n=>n+1)}><Trash2 size={16}/>Record waste</Button><Button type="button" variant="outline" aria-label={theme==='dark'?'Switch to light mode':'Switch to dark mode'} onClick={toggleTheme}>{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>}</Button></div><MenuWasteRecorder companyId={companyId} email={email} role="employee" page={page==='waste'} launchCount={wasteLaunch} refreshKey={refresh} onSection={()=>setPage('waste')} onEnabledChange={setWasteEnabled} onDirtyChange={onDirtyChange} onSaved={()=>setRefresh(n=>n+1)}/>{page==='inventory'&&<><h1>Company inventory, recipes & sales</h1><p>You can record café-item or ingredient waste when enabled. Counts, setup, and purchasing require a manager.</p>{error&&<p role="alert">{error}</p>}{!data&&!error&&<p>Loading…</p>}<h2>Catalog & stock</h2>{data?.products.map(p=>{const r=data.records.find(r=>r.productId===p.id);return <p key={p.id}><strong>{p.name}</strong> — {p.pack} — {r?r.onHand+' '+r.settings.unit:'No opening count'}</p>;})}<h2>Recipes</h2>{data?.recipes.map(r=><section key={r.id}><h3>{r.name}</h3>{r.ingredients.map(i=><p key={i.productId}>{data.products.find(p=>p.id===i.productId)?.name||i.productId}: {i.quantity} {i.unit}</p>)}</section>)}<h2>Recent sales status</h2>{data?.events.map((event,index)=><p key={index}><strong>{event.state}</strong> — {new Date(event.occurredAt).toLocaleString()}</p>)}{data&&!data.events.length&&<p>No exact sales events yet.</p>}</>}<a href="/auth/signout">Sign out</a></main>;
}
