'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
type State={members:{user_id:string;email:string|null;role:string}[];invitations:{id:string;email:string;role:string;expires:number;consumed_at:number|null;revoked_at:number|null}[];transfers:{id:string;to_user:string;expires:number}[];audit:{actor:string;action:string;target:string;created:number}[]};
export default function MembersPanel({companyId,owner}:{companyId:string;owner:boolean}){
  const [data,setData]=useState<State|null>(null),[email,setEmail]=useState(''),[role,setRole]=useState('employee'),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[link,setLink]=useState(''),[busy,setBusy]=useState(false);
  async function load(){try{const r=await fetch('/api/members?companyId='+encodeURIComponent(companyId)),d=await r.json() as State & {error?:string};if(!r.ok)throw new Error(d.error);setData(d);}catch(e){setMessage((e as Error).message);}}
  useEffect(()=>{void load();},[companyId]);
  async function send(body:Record<string,unknown>){setBusy(true);setMessage('');setLink('');try{const r=await fetch('/api/members',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,companyId})}),d=await r.json() as {error?:string;token?:string};if(!r.ok)throw new Error(d.error);if(d.token)setLink(location.origin+'/invite#token='+d.token);setMessage('Saved.');await load();if(body.action==='acceptTransfer')location.reload();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  async function reauthenticate(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'reauthenticate',password})}),d=await r.json() as {error?:string;token?:string};if(!r.ok)throw new Error(d.error);setMessage('Identity confirmed for five minutes.');}catch(e){setMessage((e as Error).message);}finally{setPassword('');setBusy(false);}}
  return <section className="product-form"><h2>Members & ownership</h2>{message&&<p role="status">{message}</p>}{owner&&<><form className="product-form" onSubmit={e=>{e.preventDefault();void send({action:'invite',email,role});}}><label>Invitation email<Input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Role <select value={role} onChange={e=>setRole(e.target.value)}><option value="employee">Employee</option><option value="manager">Manager</option></select></label><Button disabled={busy}>Create invitation link</Button><p>Share the link privately with the invited person. It expires in seven days. Creating a replacement revokes earlier invitations for that email.</p></form>{link&&<label>Copy this link now<Input readOnly value={link} onFocus={e=>e.target.select()}/></label>}
    {data?.members.map(m=><div key={m.user_id}><strong>{m.email||m.user_id}</strong> — {m.role}{m.role!=='owner'&&<div className="company-actions"><Button disabled={busy} onClick={()=>void send({action:'role',userId:m.user_id,role:m.role==='manager'?'employee':'manager'})}>Make {m.role==='manager'?'employee':'manager'}</Button><Button disabled={busy} onClick={()=>{if(confirm('Remove this member from this company?'))void send({action:'remove',userId:m.user_id});}}>Remove</Button><Button disabled={busy||!m.email} onClick={()=>{if(confirm('Offer ownership to this member? You become a manager when they accept.'))void send({action:'transfer',userId:m.user_id});}}>Offer ownership</Button></div>}</div>)}
    <h3>Invitations</h3>{data?.invitations.map(i=><div key={i.id}>{i.email} — {i.role} — {i.consumed_at?'Accepted':i.revoked_at?'Revoked':i.expires<Date.now()?'Expired':'Pending'} {!i.consumed_at&&!i.revoked_at&&<Button disabled={busy} onClick={()=>void send({action:'revoke',id:i.id})}>Revoke</Button>}</div>)}
  </>}
  <form onSubmit={reauthenticate} className="product-form"><h3>Confirm identity for ownership changes</h3><label>Current password<Input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><Button disabled={busy}>Confirm identity</Button></form>
  {data?.transfers.map(t=><div key={t.id}><p>Ownership offer expires {new Date(t.expires).toLocaleString()}.</p><Button disabled={busy} onClick={()=>{if(confirm('Accept responsibility as company owner? The previous owner becomes a manager.'))void send({action:'acceptTransfer',id:t.id});}}>Accept ownership</Button>{owner&&<Button disabled={busy} onClick={()=>void send({action:'cancelTransfer',id:t.id})}>Cancel offer</Button>}</div>)}
  {owner&&<details><summary>Security history</summary>{data?.audit.map((a,i)=><p key={i}>{new Date(a.created).toLocaleString()} — {a.action} — {a.actor}</p>)}</details>}
  </section>;
}
