'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {ChevronRight} from 'lucide-react';
import './task-form.css';
import type {InventoryManagementView,RecipeVersionView} from '@/lib/inventory-management-contract';
import {unitLabel} from '@/lib/inventory-quantities';
import type {Product} from '@/lib/pantry';

export default function RecipeList({companyId,view,products,canManage,loading,onReload,onEdit}:{companyId:string;view:InventoryManagementView;products:Product[];canManage:boolean;loading:boolean;onReload:()=>Promise<void>;onEdit:(version:RecipeVersionView)=>void;onDirtyChange:(id:string,dirty:boolean)=>void}){
  const [search,setSearch]=useState(''),[page,setPage]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const names=(id:string)=>products.find(p=>p.id===id)?.name??'Unavailable ingredient';
  const lineages=[...new Set(view.recipes.map(r=>r.recipeId))];
  const recipes=lineages.map(id=>view.recipes.find(r=>r.recipeId===id&&r.status==='active')??view.recipes.find(r=>r.recipeId===id&&r.status==='draft')??view.recipes.find(r=>r.recipeId===id)!).filter(r=>r.name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>a.name.localeCompare(b.name));
  const current=Math.min(page,Math.max(0,Math.ceil(recipes.length/10)-1));
  async function archive(r:RecipeVersionView){if(!window.confirm(`Archive ${r.name}? It will remain in history.`))return;setBusy(true);setError('');try{const response=await fetch('/api/inventory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'archiveRecipeExact',companyId,recipeId:r.recipeId,versionId:r.versionId})});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error??'Could not archive recipe.');await onReload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <div className="recipe-browser task-form"><div className="recipe-list-toolbar"><label className="recipe-list-search">Find a recipe<Input placeholder="Search recipes…" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label><p>{recipes.length} {recipes.length===1?'recipe':'recipes'}</p></div>{error&&<p role="alert" className="error">{error}</p>}<div className="compact-recipe-list">{recipes.slice(current*10,current*10+10).map(r=><details className="compact-recipe" key={r.recipeId}><summary><ChevronRight size={18} aria-hidden="true"/><span><strong>{r.name}</strong><small>{r.ingredients.length} fixed ingredients · {r.choices?.length??0} choices</small></span><span className="sample-tag">{r.status} · v{r.version}</span></summary><div className="compact-recipe-detail"><h3>Ingredients per item</h3><dl className="task-review-lines">{r.ingredients.map(i=><div key={i.productId}><dt>{names(i.productId)}</dt><dd>{i.amount} {unitLabel(i.unitId)}</dd></div>)}</dl>{r.choices?.map(g=><p key={g.id}><strong>{g.name}</strong> · choose one: {g.modifierIds.map(id=>view.modifiers.find(m=>m.recipeId===r.recipeId&&m.modifierId===id)?.name??'Unavailable option').join(', ')}</p>)}
    <p>Extras & substitutions: {view.modifiers.filter(m=>m.recipeId===r.recipeId&&m.status==='active').map(m=>m.name).join(', ')||'None'}</p>
    <div className="recipe-detail-actions">{canManage&&r.status!=='archived'&&<Button type="button" variant="outline" disabled={busy||loading} onClick={()=>onEdit(r)}>Edit recipe</Button>}
    {canManage&&r.status==='active'&&<Button type="button" variant="ghost" disabled={busy||loading} onClick={()=>void archive(r)}>Archive recipe</Button>}</div>
    <details className="modifier-history"><summary>Recipe and modifier history</summary>{view.recipes.filter(v=>v.recipeId===r.recipeId).map(v=><article key={v.versionId}><strong>Recipe v{v.version} · {v.status}</strong><ul>{v.ingredients.map(i=><li key={i.productId}>{i.amount} {unitLabel(i.unitId)} {names(i.productId)}</li>)}</ul>{v.choices?.map(g=><p key={g.id}>{g.name} · choose one</p>)}</article>)}{view.modifiers.filter(v=>v.recipeId===r.recipeId).map(v=><article key={v.versionId}><strong>{v.name} v{v.version} · {v.status}</strong><ul>{v.deltas.map((i,n)=><li key={n}>{i.amount} {unitLabel(i.unitId)} {names(i.productId)}</li>)}</ul></article>)}</details></div></details>)}</div>{!recipes.length&&<div className="recipe-empty"><h3>{search?'No matching recipes':'Your recipes start here'}</h3><p>{search?'Try another name or clear your search.':canManage?'Create a recipe with the ingredients for one menu item. Its quantities will be used when recording sales and waste.':'An owner or manager can create recipes for your menu items.'}</p>{search&&<Button variant="ghost" onClick={()=>{setSearch('');setPage(0);}}>Clear search</Button>}</div>}<div className="recipe-pagination"><span>{recipes.length} recipes · page {current+1} of {Math.max(1,Math.ceil(recipes.length/10))}</span><Button variant="outline" disabled={!current} onClick={()=>setPage(current-1)}>Previous</Button><Button variant="outline" disabled={(current+1)*10>=recipes.length} onClick={()=>setPage(current+1)}>Next</Button></div>
  {view.legacyRecipeIds.map(id=>{const legacy=view.legacyRecipes?.find(r=>r.recipeId===id);return <div className="compact-recipe-detail" key={id}><p>{legacy?.name??id}: review this older recipe before relying on its sales.</p>{canManage&&legacy&&<Button variant="outline" disabled={busy||loading} onClick={()=>onEdit({recipeId:id,versionId:legacy.versionId,name:legacy.name,version:0,status:'active',activeFrom:null,activeTo:null,ingredients:[]})}>Review older recipe</Button>}</div>;})}</div>;
}
