'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import type {InventoryManagementView,RecipeVersionView,RecipeAmountInput,RecipeChoiceGroup} from '@/lib/inventory-management-contract';
import {CURATED_UNIT_IDS,curatedUnit,formatCanonical,unitLabel} from '@/lib/inventory-quantities';
import {modifierChanges,type ModifierChange} from '@/lib/modifier-editor';
import {sendSaveRequest} from '@/lib/waste-client';
import type {Product} from '@/lib/pantry';

type Rule={modifierId:string;versionId:string;name:string;existing:boolean;changes:ModifierChange[]};
type Model={operationId:string;recipeId:string;versionId:string;name:string;expectedActiveVersionId:string|null;expectedModifiers:Record<string,string>;ingredients:RecipeAmountInput[];choices:RecipeChoiceGroup[];rules:Rule[]};
export default function RecipeBuilder({companyId,view,products,editing,onReload,onSaved,onDirtyChange}:{companyId:string;view:InventoryManagementView;products:Product[];editing:RecipeVersionView|null;onReload:()=>Promise<void>;onSaved:()=>void;onDirtyChange:(dirty:boolean)=>void}){
  const blank=():RecipeAmountInput=>({productId:'',amount:'',unitId:'mL'});
  const create=():Model=>{
    const mods=editing?view.modifiers.filter(m=>m.recipeId===editing.recipeId&&m.status==='active'):[];
    return {operationId:crypto.randomUUID(),recipeId:editing?.recipeId??crypto.randomUUID(),versionId:crypto.randomUUID(),name:editing?.name??'',expectedActiveVersionId:editing?.status==='active'?editing.versionId:null,expectedModifiers:Object.fromEntries(mods.map(m=>[m.modifierId,m.versionId])),ingredients:editing?.ingredients.length?editing.ingredients.map(i=>({productId:i.productId,amount:formatCanonical(i.quantity),unitId:{mass:'g',volume:'mL',count:'each'}[i.quantity.dimension]})):[blank()],choices:editing?.choices??[],rules:mods.map(m=>({modifierId:m.modifierId,versionId:crypto.randomUUID(),name:m.name,existing:true,changes:modifierChanges(m)}))};
  };
  const [model,setModel]=useState<Model>(create),[review,setReview]=useState(false),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState<Record<string,unknown>|null>(null),[saved,setSaved]=useState(false);
  const lock=useRef(false);
  const name=(id:string)=>products.find(p=>p.id===id)?.name??'Unavailable ingredient';
  useEffect(()=>{onDirtyChange(dirty||!!pending);return()=>onDirtyChange(false);},[dirty,pending,onDirtyChange]);
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty||pending){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty,pending]);
  function update(change:Partial<Model>){setModel(old=>({...old,...change}));setDirty(true);setReview(false);setError('');}
  const rules=(id:string,change:Partial<Rule>)=>update({rules:model.rules.map(r=>r.modifierId===id?{...r,...change}:r)});
  function amountFields(value:RecipeAmountInput,onChange:(v:RecipeAmountInput)=>void,allowRemove=false){const record=view.records.find(r=>r.productId===value.productId);return <div className="recipe-amount-fields"><label>Ingredient<select required value={value.productId} onChange={e=>{const r=view.records.find(r=>r.productId===e.target.value);onChange({...value,productId:e.target.value,unitId:r?{mass:'g',volume:'mL',count:'each'}[r.dimension]:''});}}><option value="">Choose stocked ingredient</option>{view.records.map(r=><option key={r.productId} value={r.productId}>{name(r.productId)}</option>)}</select></label>{!allowRemove&&<label>Quantity<Input required inputMode="decimal" value={value.amount} onChange={e=>onChange({...value,amount:e.target.value})}/></label>}<label>Unit<select required value={value.unitId} onChange={e=>onChange({...value,unitId:e.target.value})}>{record&&!CURATED_UNIT_IDS.some(id=>id===record.stockUnitId)&&<option value={record.stockUnitId}>{record.stockUnitLabel}</option>}{CURATED_UNIT_IDS.filter(id=>!record||curatedUnit(id).dimension===record.dimension).map(id=><option key={id} value={id}>{unitLabel(id)}</option>)}</select></label>{allowRemove&&<span>Per item</span>}</div>;}
  function addRule(sourceId?:string){const source=view.modifiers.find(m=>m.versionId===sourceId);update({rules:[...model.rules,{modifierId:crypto.randomUUID(),versionId:crypto.randomUUID(),name:source?.name??'',existing:false,changes:source?modifierChanges(source):[{...blank(),direction:'add'}]}]});}
  function addChoice(){const options=['Whole milk','Oat milk'].map(label=>({modifierId:crypto.randomUUID(),versionId:crypto.randomUUID(),name:label,existing:false,changes:[{...blank(),direction:'add' as const}]}));update({rules:[...model.rules,...options],choices:[...model.choices,{id:crypto.randomUUID(),name:'Milk choice',modifierIds:options.map(o=>o.modifierId)}]});}
  function request(){return {action:'publishRecipeExact',companyId,operationId:model.operationId,recipeId:model.recipeId,versionId:model.versionId,name:model.name.trim(),expectedActiveVersionId:model.expectedActiveVersionId,expectedModifiers:model.expectedModifiers,ingredients:model.ingredients,choices:model.choices,modifiers:model.rules.map(r=>({modifierId:r.modifierId,versionId:r.versionId,name:r.name.trim(),deltas:r.changes.map(({direction,...c})=>({...c,signed:direction==='remove'}))}))};}
  async function save(){if(lock.current)return;lock.current=true;setBusy(true);setError('');const body=pending??request();setPending(body);try{const outcome=await sendSaveRequest('/api/inventory',body,fetch,!!pending);if(outcome.kind==='saved'){setSaved(true);setPending(null);setDirty(false);try{await onReload();onSaved();}catch{setError('Recipe saved. Refresh the list before making another change.');}}else {setError(outcome.message);if(outcome.kind==='rejected')setPending(null);}}finally{lock.current=false;setBusy(false);}}
  const grouped=new Set(model.choices.flatMap(g=>g.modifierIds));
  const disabled=busy||!!pending||saved;
  return <form className="recipe-builder" onSubmit={e=>{e.preventDefault();setReview(true);setError('');}}>
    <h2>{editing?'Edit recipe':'Create recipe'}</h2><p>Enter ingredients per item, then set up the choices and extras customers can order.</p>{editing&&!editing.ingredients.length&&<p>This older recipe needs reviewed ingredient quantities. Saving keeps its existing recipe links.</p>}
    {error&&<p className="error" role="alert">{error}</p>}
    <fieldset disabled={disabled}><label>Recipe name<Input required maxLength={100} value={model.name} onChange={e=>update({name:e.target.value})}/></label>
    <h3>Ingredients in every item</h3><p>For milk alternatives, use Milk choice below instead of adding milk here.</p>
    {model.ingredients.map((i,index)=><div className="builder-row" key={index}>{amountFields(i,v=>update({ingredients:model.ingredients.map((old,n)=>n===index?v:old)}))}<Button type="button" variant="ghost" disabled={model.ingredients.length===1} onClick={()=>update({ingredients:model.ingredients.filter((_,n)=>n!==index)})}>Remove ingredient</Button></div>)}
    <Button type="button" variant="outline" onClick={()=>update({ingredients:[...model.ingredients,blank()]})}>Add ingredient</Button>
    <h3>Customer choices</h3><p>Choose one option per item. Each option adds only the selected ingredient.</p>
    {model.choices.map(g=>{const options=model.rules.filter(r=>g.modifierIds.includes(r.modifierId)),first=options[0]?.changes[0];return <div className="builder-row" key={g.id}><label>Choice name<Input required value={g.name} onChange={e=>update({choices:model.choices.map(c=>c.id===g.id?{...c,name:e.target.value}:c)})}/></label><label>Quantity per item<Input required inputMode="decimal" value={first?.amount??''} onChange={e=>update({rules:model.rules.map(r=>g.modifierIds.includes(r.modifierId)?{...r,changes:r.changes.map(c=>({...c,amount:e.target.value}))}:r)})}/></label>
      {options.map(r=><div className="builder-row" key={r.modifierId}><label>Option name<Input required readOnly={r.existing} value={r.name} onChange={e=>rules(r.modifierId,{name:e.target.value})}/></label>{amountFields(r.changes[0],v=>rules(r.modifierId,{changes:[{...v,amount:first?.amount??v.amount,direction:'add'}]}),true)}<Button type="button" variant="ghost" disabled={options.length<=2} onClick={()=>update({rules:model.rules.filter(m=>m.modifierId!==r.modifierId),choices:model.choices.map(c=>c.id===g.id?{...c,modifierIds:c.modifierIds.filter(id=>id!==r.modifierId)}:c)})}>Remove option</Button></div>)}
      <Button type="button" variant="outline" disabled={model.rules.length>=16} onClick={()=>{const id=crypto.randomUUID();update({rules:[...model.rules,{modifierId:id,versionId:crypto.randomUUID(),name:'',existing:false,changes:[{...blank(),amount:first?.amount??'',direction:'add'}]}],choices:model.choices.map(c=>c.id===g.id?{...c,modifierIds:[...c.modifierIds,id]}:c)})}}>Add milk option</Button><Button type="button" variant="ghost" onClick={()=>update({choices:model.choices.filter(c=>c.id!==g.id),rules:model.rules.filter(r=>!g.modifierIds.includes(r.modifierId))})}>Remove choice group</Button>
    </div>;})}
    <Button type="button" variant="outline" disabled={model.rules.length>14} onClick={addChoice}>Add milk choice</Button>
    <h3>Optional extras and substitutions</h3>
    <label>Reuse an existing modifier<select value="" disabled={model.rules.length>=16} onChange={e=>addRule(e.target.value)}><option value="">Choose a rule to copy</option>{view.modifiers.filter(m=>m.status==='active'&&m.recipeId!==model.recipeId).map(m=><option key={m.versionId} value={m.versionId}>{m.name} · {view.recipes.find(r=>r.recipeId===m.recipeId)?.name}</option>)}</select></label>
    {model.rules.filter(r=>!grouped.has(r.modifierId)).map(r=><div className="builder-row" key={r.modifierId}><label>Modifier name<Input required readOnly={r.existing} value={r.name} onChange={e=>rules(r.modifierId,{name:e.target.value})}/></label>{r.changes.map((c,index)=><div className="builder-row" key={index}><label>Change<select value={c.direction} onChange={e=>rules(r.modifierId,{changes:r.changes.map((old,n)=>n===index?{...old,direction:e.target.value as 'add'|'remove'}:old)})}><option value="add">Add</option><option value="remove">Remove</option></select></label>{amountFields(c,v=>rules(r.modifierId,{changes:r.changes.map((old,n)=>n===index?{...v,direction:c.direction}:old)}))}<Button type="button" variant="ghost" disabled={r.changes.length===1} onClick={()=>rules(r.modifierId,{changes:r.changes.filter((_,n)=>n!==index)})}>Remove change</Button></div>)}<Button type="button" variant="outline" onClick={()=>rules(r.modifierId,{changes:[...r.changes,{...blank(),direction:'add'}]})}>Add ingredient change</Button><Button type="button" variant="ghost" onClick={()=>update({rules:model.rules.filter(m=>m.modifierId!==r.modifierId)})}>Remove modifier</Button></div>)}
    <Button type="button" variant="outline" disabled={model.rules.length>=16} onClick={()=>addRule()}>Add modifier</Button><Button type="submit">Review recipe</Button></fieldset>
    {review&&<section className="builder-review"><h3>Review {model.name}</h3><ul>{model.ingredients.map(i=><li key={i.productId}>{i.amount} {unitLabel(i.unitId)} {name(i.productId)}</li>)}</ul>{model.choices.map(g=><div key={g.id}><strong>{g.name}: choose one</strong><ul>{model.rules.filter(r=>g.modifierIds.includes(r.modifierId)).map(r=><li key={r.modifierId}>{r.name}: {r.changes.map(c=>`${c.amount} ${unitLabel(c.unitId)} ${name(c.productId)}`).join(', ')}</li>)}</ul></div>)}{model.rules.filter(r=>!grouped.has(r.modifierId)).map(r=><p key={r.modifierId}>{r.name}: {r.changes.map(c=>`${c.direction} ${c.amount} ${unitLabel(c.unitId)} ${name(c.productId)}`).join(', ')}</p>)}<p>Saving makes this recipe and its choices available together. Previous versions remain in history.</p><Button type="button" disabled={busy||saved} onClick={()=>void save()}>{busy?'Saving…':pending?'Retry same recipe save':'Save recipe'}</Button></section>}
    {!disabled&&<Button type="button" variant="ghost" onClick={()=>{if(!dirty||window.confirm('Discard this recipe edit?'))onSaved();}}>Cancel</Button>}
    {saved&&<Button type="button" variant="outline" onClick={()=>void onReload().then(onSaved).catch(()=>setError('Could not refresh. Try again.'))}>Refresh recipe list</Button>}
  </form>;
}
