'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {registerProviders,defaultRegister,registerName,type RegisterSettings} from '@/lib/register-providers';
import CloverConnection from './clover-connection';
export default function RegisterProvider({companyId,onMap}:{companyId:string;onMap:(item:{id:string;name:string},merchantId:string,provider?:string)=>void}){
 const [saved,setSaved]=useState<RegisterSettings|null>(null),[draft,setDraft]=useState(defaultRegister),[enabled,setEnabled]=useState(false),[last,setLast]=useState<string|null>(null),[token,setToken]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[confirm,setConfirm]=useState<'token'|'revoke'|null>(null);
 async function load(){const r=await fetch('/api/register?companyId='+encodeURIComponent(companyId));const d=await r.json() as {error?:string;settings:RegisterSettings;bridgeEnabled:boolean;lastReceived:string|null};if(!r.ok)throw new Error(d.error||'Unable to load settings.');setSaved(d.settings);setDraft(d.settings);setEnabled(d.bridgeEnabled);setLast(d.lastReceived);}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[companyId]);
 async function action(action:string){if(busy)return;setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({companyId,action,settings:draft})});const d=await r.json() as {error?:string;token?:string};if(!r.ok)throw new Error(d.error||'Unable to save.');if(action!=='save')setToken(d.token||'');setConfirm(null);setNotice(action==='save'?'Provider saved for this company.':action==='token'?'New access token created. Copy it now; it will not be shown again.':'Sales endpoint access revoked.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const endpoint=typeof window==='undefined'?'':window.location.origin+'/api/register/ingest?companyId='+encodeURIComponent(companyId);
 return <><section className="catalog-card" style={{margin:'24px 0'}}><h2>This company’s register</h2><p>Select the POS used by this business. Provider selection stores your preference; connection availability is shown below.</p>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}
 <form className="product-form" onSubmit={e=>{e.preventDefault();void action('save');}}><label>Register provider<Select value={draft.provider} onValueChange={provider=>setDraft({...draft,provider})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{registerProviders.map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></label>
 {draft.provider==='other'&&<label>Custom POS name<Input required maxLength={60} value={draft.customName} onChange={e=>setDraft({...draft,customName:e.target.value})}/></label>}<label>Default location reference (optional)<Input maxLength={100} value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})}/></label><Button disabled={busy||!saved}>Save register settings</Button></form>
 {saved&&<p><strong>{registerName(saved)}</strong>: {saved.provider==='clover'?'Clover authorization and menu loading are available below. Dedicated sales sync is still pending.':'Dedicated live integration is not implemented. Use the common sales endpoint through an adapter, or import the standard CSV format below.'}</p>}{saved&&<Button variant="outline" onClick={()=>onMap({id:'',name:''},saved.location,registerName(saved))}>Add a mapping for this register</Button>}
 </section>{saved?.provider==='clover'&&<CloverConnection companyId={companyId} onMap={onMap}/>}
 <section className="catalog-card" style={{margin:'24px 0'}}><h2>Common sales endpoint</h2><span className="sample-tag">{enabled?'Access token enabled':'Access disabled'}</span><p>An integration service can translate your POS sales into Pantrack’s standard format and send them here automatically. This requires an adapter for that POS; Pantrack does not automatically read every register. Only send prepared item quantities after your opening inventory count.</p>
 <p>Last accepted request: {last?new Date(last).toLocaleString():'None received'}</p><label>Company endpoint<Input readOnly value={endpoint}/></label>
 <div className="inventory-actions" style={{marginTop:16}}><Button disabled={busy||!saved} onClick={()=>enabled?setConfirm('token'):void action('token')}>{enabled?'Replace access token':'Create access token'}</Button>{enabled&&<Button variant="outline" disabled={busy} onClick={()=>setConfirm('revoke')}>Revoke access</Button>}<a href="/register-integration-guide.md" target="_blank" rel="noreferrer">Integration instructions</a></div>
 {token&&<div className="payment-callout"><label>Access token — shown once<Input readOnly type="password" value={token}/></label><Button variant="outline" onClick={()=>void navigator.clipboard.writeText(token).then(()=>setNotice('Token copied.')).catch(()=>setError('Copy failed. Select and copy the token field.'))}>Copy token</Button><p>This token authorizes inventory deductions for this company. Store it in your integration service’s secret settings.</p></div>}
 </section><AlertDialog open={!!confirm} onOpenChange={v=>!v&&!busy&&setConfirm(null)}><AlertDialogContent><AlertDialogTitle>{confirm==='token'?'Replace access token?':'Revoke endpoint access?'}</AlertDialogTitle><AlertDialogDescription>The current token will stop working. Update your integration service before expecting new sales to arrive. Previously accepted sales remain recorded.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><Button disabled={busy} onClick={()=>confirm&&void action(confirm)}>Confirm</Button></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
