'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';

type Event={eventKey:string;state:string;sourceKind:string;provider:string;externalReference:string;eventType:string;occurredAt:string;receivedAt:string;timeQuality:string;revision:number;lastReason:string|null};
type Correction={correctionId:string;eventKey:string;status:string;reason:string;items:Array<{productId:string;dimension:string;suggestedMinor:string;approvedMinor:string}>};
type Data={enabled:boolean;events:Event[];conflicts:Array<{conflictId:string;eventKey:string;receivedAt:string;reason:string;resolved:boolean}>;corrections:Correction[]};
const localNow=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);

export default function SalesExceptions({companyId,role,recipes,onInventoryReload}:{companyId:string;role:string;recipes:Array<{recipeId:string;name:string}>;onInventoryReload:()=>Promise<void>}){
 const canManage=role==='owner'||role==='manager';
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[reason,setReason]=useState('Reviewed by manager'),[confirmedAt,setConfirmedAt]=useState(localNow()),[reference,setReference]=useState(''),[occurredAt,setOccurredAt]=useState(localNow()),[quantities,setQuantities]=useState<Record<string,number>>({}),[source,setSource]=useState<'manual'|'recipe_csv'>('manual'),[amounts,setAmounts]=useState<Record<string,string>>({});
 async function load(){try{const response=await fetch('/api/sales/events?companyId='+encodeURIComponent(companyId)),next=await response.json() as Data&{error?:string};if(!response.ok)throw new Error(next.error||'Could not load sales events.');setData(next);setAmounts(Object.fromEntries(next.corrections.flatMap(correction=>correction.items.map(item=>[correction.correctionId+':'+item.productId,item.approvedMinor]))));}catch(cause){setError((cause as Error).message);}}
 useEffect(()=>{let live=true;async function initialLoad(){try{const response=await fetch('/api/sales/events?companyId='+encodeURIComponent(companyId)),next=await response.json() as Data&{error?:string};if(!response.ok)throw new Error(next.error||'Could not load sales events.');if(live){setData(next);setAmounts(Object.fromEntries(next.corrections.flatMap(correction=>correction.items.map(item=>[correction.correctionId+':'+item.productId,item.approvedMinor]))));}}catch(cause){if(live)setError((cause as Error).message);}}void initialLoad();return()=>{live=false;};},[companyId]);
 async function act(body:Record<string,unknown>){if(busy)return;setBusy(true);setError('');setNotice('');try{const response=await fetch('/api/sales/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({companyId,...body})}),result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||'Sales action failed.');setNotice('Sales review action saved.');await Promise.all([load(),onInventoryReload()]);}catch(cause){setError((cause as Error).message);}finally{setBusy(false);}}
 async function importSale(event:React.FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError('');try{const lines=recipes.filter(recipe=>(quantities[recipe.recipeId]||0)>0).map(recipe=>({recipeId:recipe.recipeId,quantity:quantities[recipe.recipeId]}));const response=await fetch('/api/sales',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({companyId,action:'import',source,reference,occurredAt:new Date(occurredAt).toISOString(),lines})}),result=await response.json() as {error?:string;state?:string;replayed?:boolean};if(!response.ok)throw new Error(result.error||'Sales import failed.');setNotice(result.replayed?'This reference was already recorded; inventory was unchanged.':`Sales event saved with status ${result.state}.`);setReference('');setQuantities({});await Promise.all([load(),onInventoryReload()]);}catch(cause){setError((cause as Error).message);}finally{setBusy(false);}}
 function loadCsv(text:string){try{const rows=text.trim().split(/\r?\n/);if(rows.shift()?.trim().toLowerCase()!=='recipe_id,quantity')throw new Error('CSV header must be recipe_id,quantity.');const next:Record<string,number>={};for(const row of rows){const [recipeId,value,...rest]=row.split(',').map(part=>part.trim()),quantity=Number(value);if(rest.length||!recipes.some(recipe=>recipe.recipeId===recipeId)||!Number.isInteger(quantity)||quantity<1||quantity>10000)throw new Error('Every CSV row needs an active recipe ID and a quantity from 1 to 10,000.');next[recipeId]=(next[recipeId]||0)+quantity;}setQuantities(next);setSource('recipe_csv');setNotice('CSV loaded for review. Confirm its occurrence time before importing.');}catch(cause){setError((cause as Error).message);}}
 return <section className="sales-entry"><h2>Sales & exceptions</h2><p>Every included sales path uses the durable event log and exact inventory together. Financial refunds and cancellations never restore ingredients automatically.</p>
 {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}
 {canManage&&<form className="product-form" onSubmit={importSale}><h3>Record completed sales</h3><label>Unique reference<Input required maxLength={100} value={reference} onChange={event=>setReference(event.target.value)}/></label><label>Manager-confirmed occurrence time<Input required type="datetime-local" value={occurredAt} onChange={event=>setOccurredAt(event.target.value)}/></label><label>Load recipe CSV<Input type="file" accept=".csv,text/csv" onChange={async event=>{const file=event.target.files?.[0];event.target.value='';if(file)loadCsv(await file.text());}}/></label>{recipes.map(recipe=><label className="sales-quantity" key={recipe.recipeId}>{recipe.name}<Input type="number" min="0" max="10000" step="1" value={quantities[recipe.recipeId]||0} onChange={event=>{setSource('manual');setQuantities({...quantities,[recipe.recipeId]:Number(event.target.value)});}}/></label>)}<Button disabled={busy||!reference||!Object.values(quantities).some(value=>value>0)}>Save sale & apply exact inventory</Button></form>}
 <label>Manager action reason<Input value={reason} onChange={event=>setReason(event.target.value)} disabled={!canManage}/></label><label>Confirmed time for older bridge event<Input type="datetime-local" value={confirmedAt} onChange={event=>setConfirmedAt(event.target.value)} disabled={!canManage}/></label>
 <div className="inventory-table"><Table><TableHeader><TableRow><TableHead>Status</TableHead><TableHead>Source / reference</TableHead><TableHead>Occurrence</TableHead><TableHead>Review</TableHead></TableRow></TableHeader><TableBody>{data?.events.map(item=><TableRow key={item.eventKey}><TableCell><strong>{item.state}</strong><small>{item.lastReason||item.eventType}</small></TableCell><TableCell>{item.sourceKind} · {item.provider}<small>{item.externalReference} · revision {item.revision}</small></TableCell><TableCell>{new Date(item.occurredAt).toLocaleString()}<small>{item.timeQuality}</small></TableCell><TableCell>{canManage&&<div className="inventory-actions">{item.state==='failed'&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>void act({action:'retry',eventKey:item.eventKey,reason})}>Retry</Button>}{item.state==='held'&&<><Button size="sm" variant="outline" disabled={busy} onClick={()=>void act({action:'replay',eventKey:item.eventKey,reason})}>Replay</Button>{item.lastReason==='ambiguous_occurrence_time'&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>void act({action:'confirmOccurrence',eventKey:item.eventKey,occurredAt:new Date(confirmedAt).toISOString(),reason})}>Confirm time</Button>}<Button size="sm" variant="outline" disabled={busy} onClick={()=>void act({action:'dismiss',eventKey:item.eventKey,reason})}>Dismiss</Button></>}{item.state==='applied'&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>void act({action:'requestCorrection',eventKey:item.eventKey,reason})}>Request correction</Button>}</div>}</TableCell></TableRow>)}</TableBody></Table>{!data?.events.length&&<p className="empty">No exact sales events yet.</p>}</div>
 {!!data?.conflicts.length&&<><h3>Duplicate identity conflicts</h3>{data.conflicts.map(conflict=><article className="catalog-card" key={conflict.conflictId}><strong>{conflict.resolved?'Dismissed':'Needs review'}</strong><p>Event {conflict.eventKey.slice(0,12)}… · {new Date(conflict.receivedAt).toLocaleString()}</p>{canManage&&!conflict.resolved&&<Button variant="outline" disabled={busy} onClick={()=>void act({action:'dismissConflict',conflictId:conflict.conflictId,reason})}>Dismiss conflict</Button>}</article>)}</>}
 {!!data?.corrections.length&&<><h3>Reviewed stock corrections</h3>{data.corrections.map(correction=><article className="catalog-card" key={correction.correctionId}><span className="sample-tag">{correction.status}</span><p>{correction.reason}</p>{correction.items.map(item=><label key={item.productId}>{item.productId} ({item.dimension}; suggested {item.suggestedMinor})<Input disabled={!canManage||correction.status!=='pending'} value={amounts[correction.correctionId+':'+item.productId]??item.approvedMinor} onChange={event=>setAmounts({...amounts,[correction.correctionId+':'+item.productId]:event.target.value})}/></label>)}{canManage&&correction.status==='pending'&&<Button disabled={busy} onClick={()=>void act({action:'applyCorrection',correctionId:correction.correctionId,items:correction.items.map(item=>({productId:item.productId,minor:amounts[correction.correctionId+':'+item.productId]??item.approvedMinor}))})}>Confirm correction atomically</Button>}</article>)}</>}
 </section>;
}
