'use client';
import RegisterProvider from './register-provider';
import {parseRegisterCsv} from '@/lib/register-csv';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel} from '@/components/ui/alert-dialog';
import type {Product} from '@/lib/pantry';
import type {InventoryRecord} from '@/lib/inventory';
type Recipe={id:string;name:string;ingredients:{productId:string;quantity:number;unit:string}[]};
type Mapping={key:string;provider:string;location:string;itemId:string;name:string;recipeId:string};
const blank={provider:'',location:'',itemId:'',name:'',recipeId:''};
const localNow=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);
export default function SetupRegister({companyId,products,onNavigate}:{companyId:string;products:Product[];onNavigate:(tab:string)=>void}){
 const [recipes,setRecipes]=useState<Recipe[]>([]),[mappings,setMappings]=useState<Mapping[]>([]),[records,setRecords]=useState<InventoryRecord[]>([]),[form,setForm]=useState(blank),[editing,setEditing]=useState(false),[qty,setQty]=useState<Record<string,number>>({}),[reference,setReference]=useState(''),[occurredAt,setOccurredAt]=useState(localNow()),[exactEnabled,setExactEnabled]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[removing,setRemoving]=useState<Mapping|null>(null);
 async function read(path:string){const r=await fetch(path+'?companyId='+encodeURIComponent(companyId));const d=await r.json() as {error?:string;recipes:Recipe[];mappings:Mapping[];records:InventoryRecord[];replayed?:boolean;exactEnabled?:boolean};if(!r.ok)throw new Error(d.error||'Could not load setup.');return d;}
 async function load(){setLoading(true);try{const [sales,stock]=await Promise.all([read('/api/sales'),read('/api/inventory')]);setRecipes(sales.recipes);setMappings(sales.mappings);setRecords(stock.records);setExactEnabled(stock.exactEnabled===true);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{let live=true;async function initialLoad(){try{const query='?companyId='+encodeURIComponent(companyId),[salesResponse,stockResponse]=await Promise.all([fetch('/api/sales'+query),fetch('/api/inventory'+query)]),sales=await salesResponse.json() as {error?:string;recipes:Recipe[];mappings:Mapping[]},stock=await stockResponse.json() as {error?:string;records:InventoryRecord[];exactEnabled?:boolean};if(!salesResponse.ok||!stockResponse.ok)throw new Error(sales.error||stock.error||'Could not load setup.');if(live){setRecipes(sales.recipes);setMappings(sales.mappings);setRecords(stock.records);setExactEnabled(stock.exactEnabled===true);}}catch(e){if(live)setError((e as Error).message);}finally{if(live)setLoading(false);}}void initialLoad();return()=>{live=false;};},[companyId]);
 async function post(body:object){const r=await fetch('/api/sales',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({companyId,...body})});const d=await r.json() as {error?:string;recipes:Recipe[];mappings:Mapping[];records:InventoryRecord[];replayed?:boolean};if(!r.ok)throw new Error(d.error||'Could not save.');return d;}
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');setNotice('');try{await post({action:'mapping',mapping:form});setForm(blank);setEditing(false);setNotice('Register item mapping saved. Live register connection is still required.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(){if(!removing||busy)return;setBusy(true);setError('');try{await post({action:'removeMapping',mappingKey:removing.key});setQty(q=>{const n={...q};delete n[removing.key];return n;});setRemoving(null);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function importSales(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');setNotice('');try{const d=await post({action:'import',source:'mapped_csv',reference,occurredAt:exactEnabled?new Date(occurredAt).toISOString():undefined,lines:mappings.filter(m=>qty[m.key]>0).map(m=>({mappingKey:m.key,quantity:qty[m.key]}))});setNotice(d.replayed?'This reference was already imported. No additional stock was deducted.':'Sales imported. Recipe ingredients were deducted from estimated inventory.');setQty({});setReference('');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const real=products.filter(p=>!p.sample),configured=real.filter(p=>records.some(r=>r.productId===p.id)),counted=configured.filter(p=>records.some(r=>r.productId===p.id&&r.lastCount)),targeted=configured.filter(p=>records.some(r=>r.productId===p.id&&r.settings.targetStock!=null));
 const steps=[
 {title:'1. Enter real ingredients and suppliers',status:`${real.length} real products`,text:'Use exact supplier SKUs and pack sizes. Keep samples for practice only.',tab:'catalog'},
 {title:'2. Set opening stock and target quantities',status:`${counted.length}/${real.length} counted · ${targeted.length}/${real.length} with targets`,text:'Choose a stock unit per ingredient, record its opening count, and set the quantity you want to maintain.',tab:'inventory'},
 {title:'3. Build recipes for every menu variation',status:`${recipes.length} recipes saved`,text:'Enter ingredient quantities for each dish, drink size, and substitution. Record waste and unrecorded extras separately.',tab:'inventory'},
 {title:'4. Map register items to recipes',status:`${mappings.length} mappings saved`,text:'Use the editor below. Match exact register IDs and locations; names alone are not reliable identifiers.',tab:''},
 {title:'5. Connect and validate register sales',status:'Select provider and connection method below',text:'Choose a company-specific provider. Use an available dedicated connection, a configured sales adapter, or standard CSV imports. Validate sales and exception handling before automatic purchasing.',tab:''},
 {title:'6. Connect and test the first supplier',status:'Vendor integration and real-order testing required',text:'Configure the supplier connector, account, delivery and payment arrangements. Test availability, prices, order minimums, and delivery restrictions.',tab:'suppliers'},
 {title:'7. Reconcile deliveries and check accuracy',status:'Pilot validation required',text:'Confirm delivered quantities, shortages and waste. Compare estimated stock with physical counts before relying on automatic purchasing.',tab:'inventory'},
 {title:'8. Enable scheduled purchasing gradually',status:'Scheduler connection and end-to-end validation required',text:'Start with reviewed orders. Connect the scheduler, validate alerts and recovery, then enable automatic submission with product and spending limits.',tab:'suppliers'}
 ];
 const usage=new Map<string,{quantity:number;unit:string}>();for(const m of mappings){const n=qty[m.key]||0;if(n)for(const i of recipes.find(r=>r.id===m.recipeId)?.ingredients||[])usage.set(i.productId,{quantity:(usage.get(i.productId)?.quantity||0)+i.quantity*n,unit:i.unit});}
 return <section className="setup-register"><div className="page-heading"><div><div className="eyebrow">FROM SETUP TO AUTOMATIC RESTOCK</div><h1>Setup & register</h1><p>Follow these steps in order. Counts show saved configuration, not proof that a live connection works.</p></div><Button variant="outline" disabled={busy||loading} onClick={()=>{setError('');void load();}}>Refresh status</Button></div>
 {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}
 {loading?<p role="status">Loading setup…</p>:<div className="setup-grid">{steps.map(s=><article className="catalog-card" key={s.title}><h2>{s.title}</h2><span className="sample-tag">{s.status}</span><p>{s.text}</p>{s.tab&&<Button variant="outline" size="sm" onClick={()=>onNavigate(s.tab)}>Open settings</Button>}</article>)}</div>}
 <RegisterProvider companyId={companyId} onMap={(item,merchantId,provider)=>{setForm({provider:provider||'Clover',location:merchantId,itemId:item.id,name:item.name,recipeId:''});setEditing(false);document.getElementById('register-mapping-editor')?.scrollIntoView({behavior:'smooth'});}}/>
 <div id="register-mapping-editor" className="setup-grid setup-editors"><section className="catalog-card"><h2>{editing?'Edit recipe mapping':'Add a register item'}</h2><p>Create a separate recipe and mapping for each size or variation. Dynamic modifiers are held unless explicitly mapped. IDs are case-sensitive.</p><form className="product-form" onSubmit={save}>
 {([['provider','Register / POS name',60],['location','Register location ID',100],['itemId','Register item / variation ID',150],['name','Menu item name',100]] as const).map(([key,label,max])=><label key={key}>{label}<Input required maxLength={max} readOnly={editing&&key!=='name'} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}
 <label>Pantrack recipe<Select value={form.recipeId} onValueChange={recipeId=>setForm({...form,recipeId})}><SelectTrigger><SelectValue placeholder="Choose recipe"/></SelectTrigger><SelectContent>{recipes.map(r=><SelectItem key={r.id} value={r.id}>{r.name}</SelectItem>)}</SelectContent></Select></label>
 {!recipes.length&&<p>Create recipes in Inventory → Recipes & sales first.</p>}<div className="inventory-actions"><Button disabled={busy||loading||!form.recipeId}>Save mapping</Button>{editing&&<Button type="button" variant="outline" onClick={()=>{setEditing(false);setForm(blank);}}>Cancel edit</Button>}</div></form></section>
 <section className="catalog-card"><h2>Import mapped sales</h2><p><a href="/register-sales-template.csv" download>Download CSV template</a> · Format any register’s export to these columns before uploading.</p><label>Load sales CSV for review<Input type="file" accept=".csv,text/csv" disabled={busy||loading} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setError('');try{if(file.size>50000)throw new Error('CSV must be smaller than 50 KB.');const next=parseRegisterCsv(await file.text(),new Set(mappings.map(m=>m.key)));setQty(next);setNotice('CSV loaded into the preview. Review quantities and enter a unique reference before importing. No inventory has changed.');}catch(e){setError((e as Error).message);}}}/></label><p>Enter completed, prepared menu-item quantities once per unique batch reference. This changes inventory. Do not also import the same sales in Recipes & sales.</p><form className="product-form" onSubmit={importSales}><label>Unique sales batch reference<Input required maxLength={100} placeholder="Location ID + date + batch ID" value={reference} onChange={e=>setReference(e.target.value)}/></label>{exactEnabled&&<label>Manager-confirmed occurrence time<Input required type="datetime-local" value={occurredAt} onChange={e=>setOccurredAt(e.target.value)}/></label>}
 {mappings.map(m=><label className="sales-quantity" key={m.key}><span>{m.name}<small>{m.provider} · {m.location} · {m.itemId}</small></span><Input aria-label={'Quantity sold: '+m.name+' '+m.itemId} type="number" min="0" max="10000" step="1" value={qty[m.key]||0} onChange={e=>setQty({...qty,[m.key]:Number(e.target.value)})}/></label>)}
 {!mappings.length&&<p>Save a mapping first.</p>}{usage.size>0&&<div><h3>Ingredients to deduct</h3>{[...usage].map(([id,u])=><p key={id}>{products.find(p=>p.id===id)?.name||id}: {u.quantity.toLocaleString(undefined,{maximumFractionDigits:3})} {u.unit}</p>)}</div>}
 <Button disabled={busy||loading||!usage.size}>Import sales & deduct stock</Button><small>Maximum 20 menu lines and 20 distinct ingredients per batch. Previously used references cannot be reused for corrections.</small></form></section></div>
 <h2>Saved register mappings</h2><div className="inventory-table"><Table><TableHeader><TableRow><TableHead>Register / location</TableHead><TableHead>Menu item / ID</TableHead><TableHead>Recipe</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{mappings.map(m=><TableRow key={m.key}><TableCell>{m.provider}<small>{m.location}</small></TableCell><TableCell>{m.name}<small>{m.itemId}</small></TableCell><TableCell>{recipes.find(r=>r.id===m.recipeId)?.name||'Missing recipe'}</TableCell><TableCell><div className="inventory-actions"><Button disabled={busy} variant="outline" size="sm" onClick={()=>{setForm(m);setEditing(true);}}>Edit</Button><Button disabled={busy} variant="outline" size="sm" onClick={()=>setRemoving(m)}>Remove</Button></div></TableCell></TableRow>)}</TableBody></Table></div>
 <AlertDialog open={!!removing} onOpenChange={open=>!open&&!busy&&setRemoving(null)}><AlertDialogContent><AlertDialogTitle>Remove register mapping?</AlertDialogTitle><AlertDialogDescription>Future imports cannot use {removing?.name} until it is mapped again. Previously imported sales and inventory deductions remain recorded.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><Button disabled={busy} onClick={()=>void remove()}>Remove mapping</Button></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </section>;
}
