'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import type {Product} from '@/lib/pantry';
import type {InventoryManagementView} from '@/lib/inventory-management-contract';
import {CURATED_UNIT_IDS,curatedUnit,unitLabel} from '@/lib/inventory-quantities';
import {sendSaveRequest} from '@/lib/waste-client';
const localNow=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,19);
export default function StockEntry({companyId,products,view,initialProductId,onReload,onSaved,onDirtyChange}:{companyId:string;products:Product[];view:InventoryManagementView;initialProductId?:string;onReload:()=>Promise<void>;onSaved:()=>void;onDirtyChange:(dirty:boolean)=>void}){
 const [productId,setProductId]=useState(initialProductId??''),[name,setName]=useState(''),[supplier,setSupplier]=useState(''),[sku,setSku]=useState(''),[unit,setUnit]=useState<(typeof CURATED_UNIT_IDS)[number]>(()=>{const r=view.records.find(r=>r.productId===initialProductId);return r&&CURATED_UNIT_IDS.some(id=>id===r.stockUnitId)?r.stockUnitId as (typeof CURATED_UNIT_IDS)[number]:r?{mass:'g',volume:'mL',count:'each' as const}[r.dimension] as (typeof CURATED_UNIT_IDS)[number]:'each';}),[pack,setPack]=useState(products.find(p=>p.id===initialProductId)?.pack||'box'),[packAmount,setPackAmount]=useState(view.records.some(r=>r.productId===initialProductId)?'':'1'),[amount,setAmount]=useState(''),[action,setAction]=useState<'receive'|'count'|'use'|'incoming'|'configure'>('receive'),[time,setTime]=useState(localNow()),[note,setNote]=useState(''),[fromIncoming,setFromIncoming]=useState(false);
 const [custom,setCustom]=useState(false),[customLabel,setCustomLabel]=useState(''),[dimension,setDimension]=useState<'mass'|'volume'|'count'>('count'),[numerator,setNumerator]=useState('1'),[denominator,setDenominator]=useState('1');
 const [identity]=useState(()=>({product:crypto.randomUUID(),operation:crypto.randomUUID(),unit:crypto.randomUUID()}));
 const [dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState<Record<string,unknown>|null>(null),[saved,setSaved]=useState(false);const lock=useRef(false);
 const record=view.records.find(r=>r.productId===productId),isNew=productId==='new',setup=isNew||!!productId&&!record||action==='configure';
 useEffect(()=>{onDirtyChange(dirty||!!pending);return()=>onDirtyChange(false);},[dirty,pending,onDirtyChange]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty||pending){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty,pending]);
 function touch(){setDirty(true);setError('');}
 async function save(e:React.FormEvent){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{
 const common={companyId,productId:isNew?identity.product:productId,operationId:identity.operation,effectiveAt:new Date(time).toISOString()};
 const body=pending??(setup?{...common,action:isNew?'createStockExact':'configureExact',...(isNew?{name,supplier,sku}:{}),stockUnit:custom?{kind:'custom',id:identity.unit,label:customLabel,dimension,numerator,denominator}:{kind:'curated',id:unit},purchaseUnitLabel:pack,purchaseAmount:packAmount,...(!record?{openingAmount:amount}:{})}:{...common,action:action==='count'?'countExact':'movementExact',...(action==='count'?{}:{movement:action,fromIncoming}),amount,unitId:record!.stockUnitId,expectedVersion:record!.version,note});
 setPending(body);const outcome=await sendSaveRequest('/api/inventory',body,fetch,!!pending);
 if(outcome.kind==='saved'){setSaved(true);setPending(null);setDirty(false);try{await onReload();onSaved();}catch{setError('Stock saved. Refresh the list before making another change.');}}else{setError(outcome.message);if(outcome.kind==='rejected')setPending(null);}
 }catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}
 const disabled=busy||!!pending||saved;
 return <form className="stock-entry recipe-builder" onSubmit={save}><h2>Add stock</h2><p>Add a new ingredient or ready-made item, receive a delivery, or record what you physically counted.</p>{error&&<p role="alert" className="error">{error}</p>}<fieldset disabled={disabled} onChange={touch}>
 <label>Stock item<select required value={productId} onChange={e=>{const id=e.target.value,r=view.records.find(r=>r.productId===id);setProductId(id);setAction('receive');setAmount('');setCustom(false);setUnit(r&&CURATED_UNIT_IDS.some(u=>u===r.stockUnitId)?r.stockUnitId as typeof unit:r?{mass:'g',volume:'mL',count:'each' as const}[r.dimension] as typeof unit:'each');setPack(products.find(p=>p.id===id)?.pack||'box');setPackAmount(r?'':'1');}}><option value="">Choose an item</option><option value="new">＋ Create a new stock item</option>{products.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>
 {isNew&&<><label>Item name<Input required maxLength={150} placeholder="e.g. Croissants or oat milk" value={name} onChange={e=>setName(e.target.value)}/></label><details><summary>Supplier details (optional)</summary><label>Supplier<Input maxLength={100} value={supplier} onChange={e=>setSupplier(e.target.value)}/></label><label>Supplier SKU<Input maxLength={100} value={sku} onChange={e=>setSku(e.target.value)}/></label></details><p>Price stays unknown. Add supplier details and a price in Product catalog before preparing a purchase.</p></>}
 {record&&<label>What are you recording?<select value={action} onChange={e=>setAction(e.target.value as typeof action)}><option value="receive">Receive a delivery — adds stock</option><option value="count">Physical count — replaces the estimate</option><option value="use">Record extra ingredient use</option><option value="incoming">Set expected incoming stock</option><option value="configure">Change units or purchase pack</option></select></label>}
 {setup&&<><label>Count stock in<select value={unit} onChange={e=>setUnit(e.target.value as typeof unit)}>{CURATED_UNIT_IDS.map(id=><option value={id} key={id}>{id==='each'?'Individual items (each)':unitLabel(id)}</option>)}</select></label><label>Purchased as<Input required maxLength={100} placeholder="box, carton, bag…" value={pack} onChange={e=>setPack(e.target.value)}/></label><label>Quantity per {pack||'purchase pack'} ({custom?customLabel:unit})<Input required inputMode="decimal" value={packAmount} onChange={e=>setPackAmount(e.target.value)}/></label><details><summary>Custom measuring unit (advanced)</summary><label className="checkbox-label"><input type="checkbox" checked={custom} onChange={e=>{setCustom(e.target.checked);setDimension(curatedUnit(unit).dimension);}}/>Use a product-specific scoop or measure</label>{custom&&<><label>Measure label<Input required value={customLabel} onChange={e=>setCustomLabel(e.target.value)}/></label><label>Measures<select value={dimension} onChange={e=>setDimension(e.target.value as typeof dimension)}><option value="count">Items</option><option value="mass">Grams</option><option value="volume">Millilitres</option></select></label><label>Grams, millilitres, or items per measure<Input required inputMode="numeric" value={numerator} onChange={e=>setNumerator(e.target.value)}/></label><label>Divided by (normally 1)<Input required inputMode="numeric" value={denominator} onChange={e=>setDenominator(e.target.value)}/></label></>}</details></>}
 {productId&&(!record||!setup)&&<label>{setup?'Opening physical count':action==='count'?'Actual quantity counted':action==='incoming'?'Total expected incoming':'Quantity'} ({setup?(custom?customLabel:unit):record?.stockUnitLabel})<Input required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label>}
 {productId&&!setup&&action==='receive'&&<label className="checkbox-label"><input type="checkbox" checked={fromIncoming} onChange={e=>setFromIncoming(e.target.checked)}/>This delivery was already recorded as incoming</label>}
 {record&&setup&&<p>Changing units keeps the current balance. Use Physical count to record a new measured quantity.</p>}
 <details><summary>Time and note</summary><label>Occurred at<Input required type="datetime-local" step="1" value={time} onChange={e=>setTime(e.target.value)}/></label>{!setup&&<label>Note<Input maxLength={300} value={note} onChange={e=>setNote(e.target.value)}/></label>}</details>
 <Button disabled={!productId}>{setup?(record?'Save units and purchase pack':'Save item and opening stock'):action==='count'?'Save physical count':'Save stock update'}</Button></fieldset>
 {pending&&<Button type="button" disabled={busy} onClick={()=>void save({preventDefault(){}} as React.FormEvent)}>{busy?'Confirming…':'Retry the same stock save'}</Button>}{saved&&<Button type="button" onClick={()=>void onReload().then(onSaved).catch(()=>setError('Could not refresh. Try again.'))}>Refresh stock list</Button>}{!disabled&&<Button type="button" variant="ghost" onClick={()=>{if(!dirty||window.confirm('Discard this stock edit?'))onSaved();}}>Cancel</Button>}
 </form>;
}
