'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel} from '@/components/ui/alert-dialog';
type Status={ready:boolean;environment:string;connected:boolean;merchantId?:string;lastChecked?:string;callbackUrl:string};
type Item={id:string;name:string};
export default function CloverConnection({companyId,onMap}:{companyId:string;onMap:(item:Item,merchantId:string)=>void}){
 const [status,setStatus]=useState<Status|null>(null),[items,setItems]=useState<Item[]>([]),[offset,setOffset]=useState<number|null>(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState(false);
 async function refresh(){const r=await fetch('/api/clover?companyId='+encodeURIComponent(companyId));const d=await r.json() as Status&{error?:string};if(!r.ok)throw new Error(d.error||'Could not load Clover.');setStatus(d);}
 useEffect(()=>{void refresh().catch(e=>setError(e.message));if(new URLSearchParams(location.search).get('clover')==='failed')setError('Clover authorization was canceled or could not be verified. Check setup, then reconnect.');},[companyId]);
 async function action(action:string){if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/clover',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({companyId,action,offset:offset||0})});const d=await r.json() as {error?:string;url?:string;items?:Item[];nextOffset:number|null;merchantId:string};if(!r.ok)throw new Error(d.error||'Clover request failed.');if(d.url){window.location.assign(d.url);return;}if(action==='menu'){setItems(old=>[...new Map([...old,...(d.items||[])].map(i=>[i.id,i])).values()]);setOffset(d.nextOffset);}if(action==='disconnect'){setItems([]);setOffset(0);setConfirm(false);}await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="catalog-card" style={{margin:'24px 0'}}><div className="between"><h2>Clover register connection</h2><span className="sample-tag">{status?(status.connected?'Authorized · '+status.environment:status.ready?'Ready to connect · '+status.environment:'Developer setup required'):'Loading connection…'}</span></div>
 <p>Authorize access on Clover’s website. Pantrack stores the connection securely; your Clover password stays with Clover. This release connects your account and loads menu items. Automatic sales synchronization is not enabled yet.</p>
 {error&&<p role="alert" className="error">{error}</p>}
 {status&&!status.ready&&<div className="payment-callout"><strong>One-time setup for the Pantrack app owner</strong><p>Register Pantrack as a Clover web app, configure its callback URL and read permissions, and add its app ID and secret to the server. Start with a Clover sandbox account.</p><a href="/clover-setup-guide.md" target="_blank" rel="noreferrer">Open Clover setup instructions</a></div>}
 {status?.connected&&<p>Merchant ID: <strong>{status.merchantId}</strong><br/>Last successful contact: {status.lastChecked?new Date(status.lastChecked).toLocaleString():'Not checked'}</p>}
 <div className="inventory-actions"><Button disabled={busy||!status?.ready} onClick={()=>void action('connect')}>{status?.connected?'Reconnect Clover':'Connect Clover'}</Button>{status?.connected&&<><Button variant="outline" disabled={busy||offset===null} onClick={()=>void action('menu')}>{busy?'Contacting Clover…':items.length?'Load more menu items':'Load Clover menu'}</Button><Button variant="outline" disabled={busy} onClick={()=>setConfirm(true)}>Disconnect</Button></>}</div>
 {items.length>0&&<><h3 style={{marginTop:20}}>Clover menu — choose an item to map</h3><div style={{maxHeight:400,overflow:'auto'}}>{items.map(item=><div className="between" key={item.id} style={{padding:'10px 0',borderBottom:'1px solid #e0e6e2'}}><span>{item.name}<small>{item.id}</small></span><Button variant="outline" size="sm" onClick={()=>onMap(item,status!.merchantId!)}>Map to recipe</Button></div>)}</div><small>{items.length} items loaded. Mapping a menu item does not import sales or deduct inventory.</small></>}
 <AlertDialog open={confirm} onOpenChange={v=>!busy&&setConfirm(v)}><AlertDialogContent><AlertDialogTitle>Disconnect Clover?</AlertDialogTitle><AlertDialogDescription>Pantrack will delete the stored Clover tokens. Your recipes, mappings, and inventory remain. To revoke the app’s access at Clover, also remove it from your Clover account.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><Button disabled={busy} onClick={()=>void action('disconnect')}>Disconnect</Button></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </section>;
}
