'use client';
import {useEffect,useRef,useState} from 'react';
import {CreditCard,Plus,LockKeyhole,ExternalLink,ShieldCheck} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Skeleton} from '@/components/ui/skeleton';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel,AlertDialogFooter} from '@/components/ui/alert-dialog';
type Card={id:string;brand:string;last4:string;month:number;year:number;name:string};
type State={configured:boolean;testMode:boolean;cards:Card[];defaultId:string|null};
export default function PaymentMethods({companyId,companyName,hasDraft}:{companyId:string;companyName:string;hasDraft:boolean}){
 const [data,setData]=useState<State|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[remove,setRemove]=useState<Card|null>(null);
 const setupId=useRef(''),lock=useRef(false);
 async function action(body:Record<string,unknown>){const r=await fetch('/api/payments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,companyId})});const d=await r.json() as {url?:string;error?:string};if(!r.ok)throw new Error(d.error);return d;}
 async function load(){setLoading(true);try{const r=await fetch('/api/payments?companyId='+encodeURIComponent(companyId)),d=await r.json() as State&{error?:string};if(!r.ok)throw new Error(d.error);setData(d);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{let live=true;async function initialize(){setError('');const q=new URLSearchParams(location.search);if(q.get('company')===companyId&&q.has('payment_setup')){
 if(q.get('payment_setup')==='success'){try{await action({action:'verify',sessionId:q.get('session_id')});if(live)setMessage('Card saved securely. No payment was charged.');}catch(e){if(live)setError((e as Error).message);}}
 else if(live)setMessage('Card setup canceled.');
 const clean=new URL(location.href);clean.searchParams.delete('session_id');clean.searchParams.delete('payment_setup');history.replaceState(null,'',clean.pathname+clean.search);
 }if(live)await load();}void initialize();return()=>{live=false;};},[companyId]);
 async function addCard(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{if(!setupId.current)setupId.current=crypto.randomUUID();const d=await action({action:'setup',requestId:setupId.current});if(!d.url||new URL(d.url).origin!=='https://checkout.stripe.com')throw new Error('Unable to open secure card setup.');window.location.assign(d.url);}catch(e){setError((e as Error).message);setBusy(false);lock.current=false;}}
 async function update(actionName:'default'|'remove',id:string){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await action({action:actionName,paymentMethodId:id});setRemove(null);setMessage(actionName==='default'?'Default card updated.':'Card removed.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);lock.current=false;}}
 return <><div className="page-heading"><div><div className="eyebrow">COMPANY SETTINGS</div><h1>Payment methods</h1><p>Manage saved cards for {companyName}.</p></div><Button disabled={loading||busy||!data?.configured||hasDraft} onClick={addCard}><Plus size={17}/>{busy?'Please wait…':'Add card'}</Button></div>
 {error&&<div className="error" role="alert">{error}<Button variant="ghost" onClick={()=>{setError('');void load();}}>Retry</Button></div>}{message&&<div role="status" className="notice">{message}</div>}
 {hasDraft&&<p className="payment-callout">Save your prepared order before adding a card. Secure card setup opens on a separate page.</p>}
 {loading?<Skeleton className="h-48 w-full"/>:data&&<div className="payment-layout"><section className="payment-panel"><div className="between"><h2>Saved cards</h2><span className="sample-tag">{data.testMode?'Test mode':data.configured?'Stripe':'Setup pending'}</span></div>
 {!data.configured?<div className="payment-empty"><LockKeyhole size={34}/><h2>Secure card setup is coming next.</h2><p>The app administrator needs to connect the payment provider before cards can be added.</p><p>Your card number and security code will be entered directly on Stripe’s secure page.</p></div>:!data.cards.length?<div className="payment-empty"><CreditCard size={40}/><h2>No saved cards yet</h2><p>Add a company card using secure card setup. Saving a card does not charge it.</p></div>:<div className="saved-cards">{data.cards.map(card=><article key={card.id} className="saved-card"><CreditCard size={27}/><div className="card-details"><strong>{card.brand.toUpperCase()} ···· {card.last4}</strong><small>{card.name||'Company card'} · Expires {String(card.month).padStart(2,'0')}/{card.year}</small></div>{data.defaultId===card.id?<span className="sample-tag">Default</span>:<Button disabled={busy} variant="outline" onClick={()=>void update('default',card.id)}>Make default</Button>}<Button disabled={busy} className="remove-order" variant="ghost" onClick={()=>{setError('');setRemove(card);}}>Remove</Button></article>)}</div>}
 </section><aside className="payment-help"><ShieldCheck size={25}/><h2>Saved securely</h2><p>Stripe holds card details. Pantrack displays only the card brand, last four digits, and expiration date.</p><div className="payment-divider"/><h2>Supplier payments</h2><p>Saving a card does not connect it to supplier checkouts. Live purchases will require a supported supplier payment integration and your approval.</p><a href="https://stripe.com/privacy" target="_blank" rel="noreferrer">Stripe privacy policy <ExternalLink size={14}/></a></aside></div>}
 <AlertDialog open={!!remove} onOpenChange={open=>!open&&!busy&&setRemove(null)}><AlertDialogContent><AlertDialogTitle>Remove this card?</AlertDialogTitle><AlertDialogDescription>The card ending in {remove?.last4} will be removed from {companyName}. You can add it again through secure card setup.</AlertDialogDescription>{error&&<p className="error" role="alert">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Keep card</AlertDialogCancel><Button variant="destructive" disabled={busy} onClick={()=>remove&&void update('remove',remove.id)}>{busy?'Removing…':'Remove card'}</Button></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
