'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {defaultPolicy,type Policy,type Vendor,type Job} from '@/lib/automation-types';
import {money,type Product} from '@/lib/pantry';
import {Plus,Truck,Play,Settings2,RefreshCw} from 'lucide-react';
type State={vendors:Vendor[];policy:Policy;jobs:Job[];lastRun:string|null;schedulerConfigured:boolean};
export default function VendorAutomation({companyId,products}:{companyId:string;products:Product[]}){
 const [data,setData]=useState<State|null>(null),[policy,setPolicy]=useState<Policy>(defaultPolicy),[vendor,setVendor]=useState<Vendor|null>(null),[token,setToken]=useState(''),[clearToken,setClearToken]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[confirm,setConfirm]=useState<{action:string;id?:string;label:string}|null>(null),[scheduler,setScheduler]=useState<{url:string;token:string}|null>(null);
 const lock=useRef(false);
 async function call(body?:Record<string,unknown>){const r=await fetch('/api/automation?companyId='+encodeURIComponent(companyId),body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,companyId})}:undefined);const d=await r.json() as any;if(!r.ok)throw new Error(d.error||'Request failed');return d;}
 async function load(){setLoading(true);try{const d=await call();setData(d);setPolicy(d.policy);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function act(body:Record<string,unknown>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const d=await call(body);setNotice(d.message||'Saved.');if(d.schedulerToken)setScheduler({url:d.schedulerUrl,token:d.schedulerToken});if(body.action==='vendor'){setVendor(null);setToken('');}setConfirm(null);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);lock.current=false;}}
 function newVendor(){setError('');setToken('');setClearToken(false);setVendor({id:crypto.randomUUID(),name:'',website:'',endpoint:'',account:'',deliveryAddress:'',notes:'',enabled:false,verified:false});}
 function editVendor(v:Vendor){setError('');setToken('');setClearToken(false);setVendor({...v});}
 function policySubmit(e:React.FormEvent){e.preventDefault();if(policy.mode==='automatic')setConfirm({action:'policy',label:'Enable automatic purchasing?'});else void act({action:'policy',policy});}
 return <><div className="page-heading"><div><div className="eyebrow">VENDOR CONNECTIONS & PURCHASING RULES</div><h1>Suppliers & automation</h1><p>Add vendor information now. Connect and test each ordering service when it is ready.</p></div><Button onClick={newVendor}><Plus size={17}/>Add vendor</Button></div>
 {error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="notice" role="status">{notice}</div>}
 <Tabs defaultValue="vendors"><TabsList className="inventory-tabs"><TabsTrigger value="vendors">Vendor connections</TabsTrigger><TabsTrigger value="rules">Automation rules</TabsTrigger><TabsTrigger value="activity">Proposals & orders</TabsTrigger><TabsTrigger value="schedule">Schedule & setup</TabsTrigger></TabsList>
 <TabsContent value="vendors">{loading?<p>Loading vendor connections…</p>:<div className="catalog-grid">{data?.vendors.map(v=><article className="catalog-card" key={v.id}><Truck size={26}/><h2>{v.name}</h2><span className="status">{v.verified?'Connector verified':'Not connected / unverified'}</span><p>{v.enabled?'Included in replenishment checks':'Paused'}</p><small>Account: {v.account||'Not entered'}</small><small>{v.hasToken?'Access token saved securely':'No access token saved'}</small><p>{v.deliveryAddress||'Add a delivery address'}</p><div className="inventory-actions"><Button variant="outline" disabled={busy} onClick={()=>editVendor(v)}>Edit details</Button><Button variant="outline" disabled={busy||!v.endpoint} onClick={()=>void act({action:'test',id:v.id})}>Test connection</Button></div></article>)}</div>}{!loading&&!data?.vendors.length&&<div className="empty"><Truck size={32}/><h2>No ordering connections yet</h2><p>Your catalog supplier names are saved, but they are not connected to vendor checkout systems.</p><Button onClick={newVendor}>Add your first vendor</Button></div>}<p className="inventory-caption">Match the vendor name to the supplier name in Product catalog. A shopping website URL alone cannot submit orders. Editing a connection clears its verification.</p></TabsContent>
 <TabsContent value="rules"><form className="automation-form" onSubmit={policySubmit}><section className="catalog-card"><h2>Purchasing controls</h2><label>Mode<Select value={policy.mode} onValueChange={v=>setPolicy({...policy,mode:v as Policy['mode']})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="paused">Paused</SelectItem><SelectItem value="review">Review only — never submits automatically</SelectItem><SelectItem value="automatic">Automatic — submit within approved limits</SelectItem></SelectContent></Select></label><p>Start in review mode. Proposals remain unsent until you approve them. Automatic mode requires a verified connector and real, allowed products.</p>{([['intervalHours','Check every (hours)',1,168],['maxOrder','Maximum per order (USD)',.01,100000],['dailyLimit','Daily spending limit (USD, UTC day)',.01,100000],['priceTolerance','Maximum price increase, including delivery (%)',0,50]] as const).map(([f,l,min,max])=><label key={f}>{l}<Input required type="number" min={min} max={max} step={f==='intervalHours'?1:.01} value={f==='maxOrder'||f==='dailyLimit'?policy[f]/100:policy[f]} onChange={e=>setPolicy({...policy,[f]:f==='maxOrder'||f==='dailyLimit'?Math.round(Number(e.target.value)*100):Number(e.target.value)})}/></label>)}<p>Substitutions are never allowed. Stale counts, low-confidence estimates, expired stock, unexpected quotes, or uncertain submissions stop automatic ordering.</p></section><section className="catalog-card"><h2>Products allowed for replenishment</h2><p>Choose the exact products this company may order.</p><div className="allowed-products">{products.map(p=><label className="checkbox-label" key={p.id}><Checkbox checked={policy.allowedProducts.includes(p.id)} onCheckedChange={v=>setPolicy({...policy,allowedProducts:v===true?[...policy.allowedProducts,p.id]:policy.allowedProducts.filter(id=>id!==p.id)})}/><span>{p.name}<small>{p.supplier} · {p.sku}{p.sample?' · Sample: review only':''}</small></span></label>)}</div></section><Button type="submit" disabled={busy||loading}>Save automation rules</Button></form></TabsContent>
 <TabsContent value="activity"><div className="inventory-section-heading"><div><h2>Replenishment proposals & vendor orders</h2><p>Current mode: {data?.policy.mode||'paused'} · Last check: {data?.lastRun?new Date(data.lastRun).toLocaleString():'Never'}</p></div><div className="inventory-actions"><Button variant="outline" disabled={busy} onClick={()=>void load()}><RefreshCw size={16}/>Refresh</Button><Button disabled={busy||!data||data.policy.mode==='paused'} onClick={()=>data?.policy.mode==='automatic'?setConfirm({action:'run',label:'Run a live purchasing check?'}):void act({action:'run'})}><Play size={16}/>Run check now</Button></div></div>
 {!data?.jobs.length?<p className="empty">Save rules, enable a vendor, and run a check to generate proposals from eligible inventory.</p>:data.jobs.map(j=><article className="automation-job" key={j.id}><div className="between"><h2>{j.vendorName}</h2><span className="status">{j.status}</span><strong>{money(j.amount)}</strong></div><p>{j.message}</p><small>Reference: {j.id}</small>{j.vendorOrderId&&<small>Vendor confirmation: {j.vendorOrderId}</small>}<small>{new Date(j.created).toLocaleString()}</small>{j.items.map(i=><div className="between review-line" key={i.id}><span>{i.name} · {i.sku}</span><strong>{i.quantity} {i.unit}{i.quantity!==1?'s':''}</strong></div>)}<div className="inventory-actions">{j.status==='review'&&<><Button disabled={busy} onClick={()=>setConfirm({action:'approve',id:j.id,label:'Approve this live purchase?'})}>Approve & submit</Button><Button variant="outline" disabled={busy} onClick={()=>setConfirm({action:'dismiss',id:j.id,label:'Dismiss this unsent proposal?'})}>Dismiss</Button></>}{['sending','unknown','accepted'].includes(j.status)&&<Button disabled={busy} variant="outline" onClick={()=>void act({action:'reconcile',id:j.id})}>Check vendor status</Button>}{j.status==='accepted'&&<Button disabled={busy} variant="outline" onClick={()=>setConfirm({action:'received',id:j.id,label:'Close this delivered order?'})}>Close after receiving</Button>}</div>{j.status==='accepted'&&<p className="inventory-caption">Record actual receipts in Inventory with this proposal’s reference as the delivery note, then close here. Until then, these items are held from further automatic orders.</p>}</article>)}</TabsContent>
 <TabsContent value="schedule"><div className="automation-form"><section className="catalog-card"><Settings2 size={25}/><h2>Unattended schedule</h2><p>A background scheduler is not connected yet. “Run check now” works immediately; unattended operation requires an external scheduler to call the secure endpoint.</p><p>Configure it to send a POST at least as often as your chosen interval. The server checks when a run is due and prevents overlapping runs.</p><Button disabled={busy} onClick={()=>void act({action:'scheduler'})}>{data?.schedulerConfigured?'Rotate scheduler key':'Create scheduler key'}</Button>{scheduler&&<div className="scheduler-details"><label>POST URL<Input readOnly value={scheduler.url}/></label><label>Bearer token — copy now<Input readOnly type="password" value={scheduler.token}/></label><Button variant="outline" onClick={async()=>{try{await navigator.clipboard.writeText(scheduler.token);setNotice('Scheduler token copied.');}catch{setError('Clipboard unavailable. Select the token field to copy it manually.');}}}>Copy token</Button><small>Send as Authorization: Bearer TOKEN. Treat this key like a password. Rotating it invalidates the old key.</small></div>}</section><section className="catalog-card"><h2>Vendor connector guide</h2><p>Each supplier needs a supported ordering API or an adapter that translates its API into Pantrack’s request format.</p><p>The connector must provide current quotes, enforce maximum totals and no substitutions, submit idempotent orders, and look up confirmations.</p><a className="product-link" href="/vendor-connector-guide.md" target="_blank" rel="noreferrer">Open the connector specification</a><p>Credentials belong to this company’s vendor account. Pantrack’s Stripe card vault does not pay arbitrary suppliers.</p></section></div></TabsContent></Tabs>
 <Dialog open={!!vendor} onOpenChange={v=>!v&&!busy&&setVendor(null)}><DialogContent className="order-dialog"><DialogTitle>Vendor connection</DialogTitle><DialogDescription>Save details now and fill in the connection when your vendor or developer provides it.</DialogDescription>{vendor&&<form className="product-form" onSubmit={e=>{e.preventDefault();void act({action:'vendor',vendor,token,clearToken});}}>{([['name','Supplier name — match the product catalog'],['website','Shopping website (optional)'],['account','Vendor customer/account number'],['deliveryAddress','Full delivery address'],['endpoint','Ordering connector URL (optional)'],['notes','Notes / vendor setup instructions']] as const).map(([f,l])=><label key={f}>{l}<Input required={f==='name'} type={f==='website'||f==='endpoint'?'url':'text'} maxLength={f==='name'?100:f==='account'?200:1000} value={vendor[f]} onChange={e=>setVendor({...vendor,[f]:e.target.value})}/></label>)}<label>Connector access token (optional)<Input type="password" autoComplete="new-password" value={token} maxLength={4000} placeholder={vendor.hasToken?'Leave blank to keep saved token':'Bearer token from your connector'} onChange={e=>setToken(e.target.value)}/></label>{vendor.hasToken&&<label className="checkbox-label"><Checkbox checked={clearToken} onCheckedChange={v=>setClearToken(v===true)}/>Remove saved token</label>}<label className="checkbox-label"><Checkbox checked={vendor.enabled} onCheckedChange={v=>setVendor({...vendor,enabled:v===true})}/>Include this vendor in replenishment checks</label><p>The ordering connector is not the vendor’s shopping homepage. Tokens are encrypted and never displayed after saving.</p>{error&&<p role="alert" className="error">{error}</p>}<Button type="submit" disabled={busy}>{busy?'Saving…':'Save vendor'}</Button></form>}</DialogContent></Dialog>
 <AlertDialog open={!!confirm} onOpenChange={v=>!v&&!busy&&setConfirm(null)}><AlertDialogContent><AlertDialogTitle>{confirm?.label}</AlertDialogTitle><AlertDialogDescription>{confirm?.action==='policy'?'Future scheduled or manual checks may place real orders for your allowed products, within the limits you set. Live POS, payment and vendor compatibility must be configured separately.':confirm?.action==='received'?'Record every actual receipt in Inventory first, using this proposal’s reference as its delivery note. This action releases the replenishment hold only after those receipts are recorded.':confirm?.action==='dismiss'?'This unsent proposal will be dismissed. It will not be regenerated until the inventory snapshot changes.':'This may place a real order through the saved vendor connection, using your vendor account’s payment terms. Current spending and price rules will be checked.'}</AlertDialogDescription>{error&&<p className="error" role="alert">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><Button disabled={busy} onClick={()=>confirm&&void act({action:confirm.action,id:confirm.id,...(confirm.action==='policy'?{policy}:{})})}>{busy?'Processing…':'Confirm'}</Button></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </>;
}
