'use client';
import SetupRegister from './setup-register';
import VendorAutomation from './vendor-automation';
import ManagerOperations from './manager-operations';
import InventoryPanel from './inventory-panel';
import PaymentMethods from './payment-methods';
import {CreditCard} from 'lucide-react';
import {useEffect,useRef,useState} from 'react';
import {Package,ShoppingBag,BookOpen,History,Truck,Search,Plus,Minus,ArrowRight,Download,Check,Leaf,Pencil,AlertCircle} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel,AlertDialogFooter} from '@/components/ui/alert-dialog';
import {Skeleton} from '@/components/ui/skeleton';
import {money,suppliers,type Product,type Order} from '@/lib/pantry';
const fresh=():Product=>({id:crypto.randomUUID(),name:'',supplier:'',sku:'',pack:'',unit:'case',price:0,category:'Other',url:'',sample:false});
async function request(companyId:string,body?:Record<string,unknown>){const r=await fetch('/api/workspace?companyId='+encodeURIComponent(companyId),body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,companyId})}:undefined);const d=await r.json() as {error?:string;products:Product[];orders:Order[];order:Order;removedId?:string};if(!r.ok)throw new Error(d.error||'Unable to complete request.');return d;}
export default function Workspace({email,companyId,companyName,role,onDirtyChange}:{email:string;companyId:string;companyName:string;role:string;onDirtyChange:(dirty:boolean)=>void}){
const [tab,setTab]=useState('order'),[products,setProducts]=useState<Product[]>([]),[orders,setOrders]=useState<Order[]>([]),[qty,setQty]=useState<Record<string,number>>({}),[search,setSearch]=useState(''),[category,setCategory]=useState('All products'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[review,setReview]=useState(false),[editing,setEditing]=useState<Product|null>(null),[detail,setDetail]=useState<Order|null>(null),[notice,setNotice]=useState('');
const key=useRef(''),lock=useRef(false);
const [removing,setRemoving]=useState<Order|null>(null);
useEffect(()=>{onDirtyChange(Object.values(qty).some(n=>n>0));},[qty,onDirtyChange]);
async function load(){setLoading(true);setError('');try{const d=await request(companyId);setProducts(d.products);setOrders(d.orders);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
useEffect(()=>{void load();if(new URLSearchParams(location.search).has('payment_setup'))setTab('payments');if(new URLSearchParams(location.search).has('clover'))setTab('setup');},[]);
function quantity(id:string,n:number){if(!Number.isInteger(n)||n<0||n>999)return;setQty(q=>({...q,[id]:n}));key.current='';}
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const abort=new AbortController();Promise.resolve(context.registerTool({name:'stage_order_quantities',description:'Set quantities in the current draft for review. Does not save or send an order.',inputSchema:{type:'object',properties:{items:{type:'array',items:{type:'object',properties:{id:{type:'string'},quantity:{type:'integer',minimum:0,maximum:999}},required:['id','quantity'],additionalProperties:false}}},required:['items'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:any)=>{if(!Array.isArray(input?.items)||input.items.some((i:any)=>!products.some(p=>p.id===i.id)||!Number.isInteger(i.quantity)||i.quantity<0||i.quantity>999))throw new Error('Invalid product or quantity');setQty(q=>({...q,...Object.fromEntries(input.items.map((i:any)=>[i.id,i.quantity]))}));key.current='';setTab('order');return {staged:input.items.length,sent:false};}},{signal:abort.signal})).catch(()=>{});return ()=>abort.abort();},[products]);
const items=products.filter(p=>qty[p.id]>0).map(p=>({...p,quantity:qty[p.id]})),total=items.reduce((s,p)=>s+p.price*p.quantity,0),groups=[...new Set(items.map(p=>p.supplier))];
const shown=products.filter(p=>(category==='All products'||p.category===category)&&[p.name,p.sku,p.supplier].join(' ').toLowerCase().includes(search.toLowerCase()));
async function prepare(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{if(!key.current)key.current=crypto.randomUUID();const d=await request(companyId,{action:'prepare',id:key.current,items:items.map(p=>({id:p.id,quantity:p.quantity}))});setOrders(o=>[d.order,...o.filter(x=>x.id!==d.order.id)]);setQty({});key.current='';setReview(false);setDetail(d.order);setNotice('Order saved. Nothing has been sent to suppliers.');setTab('history');}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}
async function saveProduct(e:React.FormEvent){e.preventDefault();if(!editing||busy)return;setBusy(true);setError('');try{await request(companyId,{action:'product',product:editing});setProducts(p=>[...p.filter(x=>x.id!==editing.id),editing]);setEditing(null);setNotice('Product saved to your catalog.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
async function removeOrder(){if(!removing||lock.current)return;lock.current=true;setBusy(true);setError('');try{await request(companyId,{action:'remove',id:removing.id});setOrders(o=>o.filter(x=>x.id!==removing.id));if(detail?.id===removing.id)setDetail(null);setRemoving(null);setNotice('Prepared order removed from this company’s history.');}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}
function download(o:Order,supplier:string){const rows=[['PREPARED ORDER — NOT SENT'],['Supplier',supplier],['Order reference',o.id],['Created',o.created],['Prices are estimates; tax and delivery excluded'],['Product','SKU','Pack size','Unit','Quantity','Estimated unit price','Estimated line total'],...o.items.filter(p=>p.supplier===supplier).map(p=>[p.name,p.sku,p.pack,p.unit,p.quantity,money(p.price),money(p.price*p.quantity)])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));a.download='prepared-order-'+supplier.replace(/[^a-z0-9]/gi,'-')+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
const summary=(list:typeof items)=>[...new Set(list.map(p=>p.supplier))].map(s=>{const lines=list.filter(p=>p.supplier===s),subtotal=lines.reduce((a,p)=>a+p.quantity*p.price,0),minimum=suppliers.find(x=>x.name===s)?.minimum;return <section className="supplier-summary" key={s}><div className="between"><strong>{s}</strong><span>{money(subtotal)}</span></div>{lines.map(p=><div className="review-line" key={p.id}><span>{p.name}<small>{p.sku} · {p.pack}</small></span><strong>{p.quantity} {p.unit}{p.quantity!==1?'s':''}</strong></div>)}{minimum&&subtotal<minimum*100?<p className="warning">Below sample minimum of {money(minimum*100)}.</p>:null}<small>Not connected · price and availability unverified</small></section>;});
return <div className="app"><header className="topbar"><a className="brand" href="/"><span><Package size={22}/></span>pantrack<span className="brand-period">.</span></a><div className="workspace-name">{companyName} <span>Purchasing workspace</span></div><span className="account" title={email}>{email.split('@')[0]} <span className="avatar">{email.slice(0,1).toUpperCase()}</span></span></header>
<Tabs value={tab} onValueChange={setTab}><div className="nav-wrap"><TabsList className="main-nav" variant="line"><TabsTrigger value="order"><ShoppingBag/>New order</TabsTrigger><TabsTrigger value="inventory"><Package/>Inventory</TabsTrigger><TabsTrigger value="catalog"><BookOpen/>Product catalog</TabsTrigger><TabsTrigger value="history"><History/>Order history{orders.length>0&&<span className="count">{orders.length}</span>}</TabsTrigger><TabsTrigger value="suppliers"><Truck/>Suppliers & automation</TabsTrigger>{role==='owner'&&<TabsTrigger value="payments"><CreditCard/>Payment methods</TabsTrigger>}{role==='owner'&&<TabsTrigger value="setup"><Check/>Setup & register</TabsTrigger>}</TabsList><span className="pilot-label">PILOT WORKSPACE</span></div>
<main><div className="demo-banner"><Leaf size={17}/><span><strong>Start with a practice order.</strong> Sample products and suppliers are fictional. Real purchasing requires configured connections and enabled automation.</span></div>
{error&&<div role="alert" className="error">{error} <button onClick={()=>void load()}>Retry loading</button></div>}{notice&&<div className="notice" role="status">{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}>×</button></div>}
<TabsContent value="order"><div className="page-heading"><div><div className="eyebrow">YOUR WEEKLY RESTOCK</div><h1>A fresh start, fully stocked.</h1><p>Your regular products. All your suppliers. One order list.</p></div><div className="step-label"><span>1</span> Select products <i>—</i> 2 Review</div></div>
<div className="order-layout"><section className="product-panel"><div className="catalog-tools"><div className="search"><Search size={18}/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products, suppliers, or SKUs" aria-label="Search products"/></div><div className="filters">{['All products','Dairy','Coffee & pantry','Packaging'].map(c=><button className={category===c?'active':''} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div></div>
{loading?<div className="loading">{[1,2,3,4].map(i=><Skeleton key={i} className="h-16 w-full mb-4"/>)}</div>:<Table><TableHeader><TableRow><TableHead>Product / pack size</TableHead><TableHead>Est. price</TableHead><TableHead className="text-center">Quantity</TableHead><TableHead className="text-right">Subtotal</TableHead></TableRow></TableHeader><TableBody>{shown.map(p=><TableRow key={p.id} className={qty[p.id]?'selected-row':''}><TableCell><div className="product-name"><span className={'product-icon '+(p.category==='Dairy'?'blue':p.category==='Packaging'?'ochre':'green')}><Package size={20}/></span><div><strong>{p.name}</strong><span>{p.pack} / {p.unit}</span><small>{p.supplier} · {p.sku}</small></div></div></TableCell><TableCell><strong>{money(p.price)}</strong><small>per {p.unit}</small></TableCell><TableCell><div className="stepper"><button aria-label={'Decrease '+p.name} disabled={!qty[p.id]} onClick={()=>quantity(p.id,(qty[p.id]||0)-1)}><Minus size={14}/></button><input aria-label={'Quantity of '+p.name+' in '+p.unit+'s'} type="number" min="0" max="999" step="1" value={qty[p.id]||0} onChange={e=>quantity(p.id,Number(e.target.value))}/><button aria-label={'Increase '+p.name} disabled={qty[p.id]===999} onClick={()=>quantity(p.id,(qty[p.id]||0)+1)}><Plus size={14}/></button></div></TableCell><TableCell className="text-right">{qty[p.id]?money(p.price*qty[p.id]):<span className="muted">—</span>}</TableCell></TableRow>)}</TableBody></Table>}{!loading&&shown.length===0&&<div className="empty">No matching products. Try another search.</div>}<div className="table-foot">{shown.length} products <span>USD · prices are estimates</span></div></section>
<aside className="basket"><div className="between"><h2>Your order</h2><ShoppingBag size={21}/></div><p>{items.length} products across {groups.length} suppliers</p><div className="basket-lines">{groups.length?groups.map(s=><div key={s} className="basket-supplier"><div className="between"><strong>{s}</strong><span>{money(items.filter(p=>p.supplier===s).reduce((a,p)=>a+p.quantity*p.price,0))}</span></div><small>{items.filter(p=>p.supplier===s).length} products · Not connected</small></div>):<div className="basket-empty"><ShoppingBag size={34}/><strong>Make room for next week.</strong><span>Add quantities to start your order.</span></div>}</div><div className="between total"><span>Estimated subtotal</span><strong>{money(total)}</strong></div><small>Tax and delivery calculated by each supplier.</small><Button className="review-button" disabled={!items.length||loading} onClick={()=>{setError('');setReview(true);}}>Review order <ArrowRight size={17}/></Button><div className="basket-note"><Check size={16}/> You review every order before saving.</div></aside></div></TabsContent>
<TabsContent value="catalog"><div className="page-heading"><div><div className="eyebrow">THE RIGHT PRODUCT, EVERY TIME</div><h1>Product catalog</h1><p>Save exact SKUs, packaging, and supplier links.</p></div><Button onClick={()=>setEditing(fresh())}><Plus/>Add product</Button></div><div className="catalog-grid">{products.map(p=><article className="catalog-card" key={p.id}><div className="between"><span className="category-tag">{p.category}</span><button aria-label={'Edit '+p.name} onClick={()=>setEditing({...p})}><Pencil size={17}/></button></div><h2>{p.name}</h2><p>{p.supplier}</p><div className="pack-detail">{p.pack} / {p.unit}<small>SKU {p.sku}</small></div><div className="between"><strong>{money(p.price)} <small>/{p.unit}</small></strong><span className="sample-tag">{p.sample?'Sample':'Unverified price'}</span></div>{p.url&&<a className="product-link" href={p.url} target="_blank" rel="noreferrer">Open supplier product ↗</a>}</article>)}</div></TabsContent>
<TabsContent value="history"><div className="page-heading"><div><div className="eyebrow">A RECORD OF EVERY RESTOCK</div><h1>Order history</h1><p>Prepared orders are saved here. Supplier acceptance is not yet connected.</p></div></div>{orders.length?<div className="history-list">{orders.map(o=><article className="history-card" key={o.id}><div><strong>Order {o.id.slice(0,8).toUpperCase()}</strong><small>{new Date(o.created).toLocaleString()} · {o.items.length} products</small></div><span className="status">{o.status}</span><strong>{money(o.total)}</strong><Button variant="outline" onClick={()=>setDetail(o)}>View & export</Button>{o.status==='Prepared — not sent'&&<Button variant="ghost" className="remove-order" onClick={()=>{setError('');setRemoving(o);}}>Remove</Button>}<Button variant="ghost" onClick={()=>{setQty(Object.fromEntries(o.items.filter(i=>products.some(p=>p.id===i.id)).map(i=>[i.id,i.quantity])));key.current='';setTab('order');setNotice('Order loaded as a new draft. Current catalog prices apply.');}}>Reorder</Button></article>)}</div>:<div className="empty"><History size={35}/><h2>Your first order starts here.</h2><p>Choose products and save a reviewed order to build your history.</p><Button onClick={()=>setTab('order')}>Create an order</Button></div>}</TabsContent>
<TabsContent value="setup"><SetupRegister companyId={companyId} products={products} onNavigate={setTab}/></TabsContent>
<TabsContent value="suppliers">{role==='owner'?<VendorAutomation companyId={companyId} products={products}/>:<ManagerOperations companyId={companyId}/>}</TabsContent>
<TabsContent value="inventory"><InventoryPanel companyId={companyId} products={products} hasDraft={items.length>0} onStage={q=>{setQty(q);key.current='';setTab('order');setNotice('Replenishment plan loaded. Review quantities, prices, and suppliers before saving.');}}/></TabsContent><TabsContent value="payments"><PaymentMethods companyId={companyId} companyName={companyName} hasDraft={items.length>0}/></TabsContent>
<footer>pantrack. <span>Prepared with care. Ordered with confidence.</span><a href="/auth/signout" target="_top">Sign out</a></footer></main></Tabs>
<AlertDialog open={!!removing} onOpenChange={open=>!open&&!busy&&setRemoving(null)}><AlertDialogContent><AlertDialogTitle>Remove prepared order?</AlertDialogTitle><AlertDialogDescription>Order {removing?.id.slice(0,8).toUpperCase()} will be removed from {companyName}’s history. This cannot be undone. Nothing has been sent to a supplier.</AlertDialogDescription>{error&&<p className="error" role="alert">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Keep order</AlertDialogCancel><Button variant="destructive" disabled={busy} onClick={removeOrder}>{busy?'Removing…':'Remove order'}</Button></AlertDialogFooter></AlertDialogContent></AlertDialog>
<Dialog open={review} onOpenChange={v=>!busy&&setReview(v)}><DialogContent className="order-dialog"><DialogTitle>Review your order</DialogTitle><DialogDescription>Check quantities and pack sizes. Saving prepares an order; it does not send it or charge you.</DialogDescription>{summary(items)}<div className="between total"><span>Estimated subtotal</span><strong>{money(total)}</strong></div><p className="muted">Tax, delivery, stock, and supplier cutoffs are unverified. Sample minimums are guidance only.</p>{error&&<p className="error" role="alert">{error}</p>}<Button disabled={busy||!items.length} onClick={prepare}>{busy?'Saving…':'Save prepared order'}</Button></DialogContent></Dialog>
<Dialog open={!!detail} onOpenChange={v=>!v&&setDetail(null)}><DialogContent className="order-dialog"><DialogTitle>Order {detail?.id.slice(0,8).toUpperCase()}</DialogTitle><DialogDescription>Prepared — not sent. Download one file per supplier for review and manual ordering.</DialogDescription>{detail&&summary(detail.items)}{detail&&[...new Set(detail.items.map(p=>p.supplier))].map(s=><Button variant="outline" key={s} onClick={()=>download(detail,s)}><Download size={16}/>Export {s}</Button>)}</DialogContent></Dialog>
<Dialog open={!!editing} onOpenChange={v=>!busy&&!v&&setEditing(null)}><DialogContent className="order-dialog"><DialogTitle>{editing?.id.startsWith('sample-')?'Edit sample product':'Product details'}</DialogTitle><DialogDescription>Confirm SKU and package size with the supplier. Prices are recorded estimates.</DialogDescription>{editing&&<form onSubmit={saveProduct} className="product-form">{[['name','Product name'],['supplier','Supplier name'],['sku','Supplier SKU'],['pack','Pack size (e.g. 4 × 1 gallon)'],['unit','Order unit (e.g. case)'],['category','Category'],['url','Product URL (optional)']].map(([field,label])=><label key={field}>{label}<Input required={field!=='url'} maxLength={field==='url'?1000:150} type={field==='url'?'url':'text'} value={String(editing[field as keyof Product])} onChange={e=>setEditing({...editing,[field]:e.target.value})}/></label>)}<label>Estimated price per order unit (USD)<Input type="number" min="0" max="100000" step=".01" required value={editing.price/100} onChange={e=>setEditing({...editing,price:Math.round(Number(e.target.value)*100)})}/></label>{error&&<p role="alert" className="error">{error}</p>}<Button disabled={busy} type="submit">{busy?'Saving…':'Save product'}</Button></form>}</DialogContent></Dialog>
</div>;
}
