import {getChatGPTUser} from '@/app/chatgpt-auth';
import {database} from '@/db/raw';
import {samples, type Product} from '@/lib/pantry';
import {z} from 'zod';
import {companyAccess} from '@/lib/company-access';
const product=z.object({id:z.string().min(1).max(100),name:z.string().trim().min(1).max(150),supplier:z.string().trim().min(1).max(100),sku:z.string().trim().min(1).max(100),pack:z.string().trim().min(1).max(100),unit:z.string().trim().min(1).max(30),price:z.number().int().min(0).max(10000000),category:z.string().max(60),url:z.union([z.literal(''),z.string().url().refine(v=>v.startsWith('https://')||v.startsWith('http://'))]),sample:z.boolean()});
export async function GET(req:Request){const u=await getChatGPTUser();if(!u)return Response.json({error:'Please sign in again.'},{status:401});const companyId=new URL(req.url).searchParams.get('companyId');if(!(await companyAccess(u.userId,companyId)))return Response.json({error:'You do not have access to this company.'},{status:403});try{const db=database();const [p,o]=await Promise.all([db.prepare('SELECT data FROM products WHERE owner=? ORDER BY id').bind(companyId).all<{data:string}>(),db.prepare('SELECT data FROM orders WHERE owner=? ORDER BY created DESC').bind(companyId).all<{data:string}>()]);return Response.json({products:p.results.map(r=>JSON.parse(r.data)),orders:o.results.map(r=>JSON.parse(r.data))},{headers:{'Cache-Control':'no-store'}});}catch(e){console.error(e);return Response.json({error:'Could not load your workspace. Please retry.'},{status:503});}}
export async function POST(req:Request){const u=await getChatGPTUser();if(!u)return Response.json({error:'Please sign in again.'},{status:401});if(req.headers.get('sec-fetch-site')==='cross-site')return Response.json({error:'Invalid request origin'},{status:403});if(!req.headers.get('content-type')?.startsWith('application/json'))return Response.json({error:'JSON required'},{status:415});try{const b=await req.json() as {action?:string;product?:unknown;companyId?:string;id?:string},db=database();const companyId=b.companyId;const access=await companyAccess(u.userId,companyId);if(!access)return Response.json({error:'You do not have access to this company.'},{status:403});if(!['owner','manager'].includes(access.role))return Response.json({error:'You do not have permission to change orders or products.'},{status:403});if(b.action==='remove'){
const id=z.string().uuid().parse(b.id);
await db.batch([
db.prepare("INSERT OR IGNORE INTO removed_orders(company_id,order_id,removed_by,removed_at) SELECT owner,id,?,? FROM orders WHERE owner=? AND id=? AND json_extract(data,'$.status')=?").bind(u.userId,new Date().toISOString(),companyId,id,'Prepared — not sent'),
db.prepare("DELETE FROM orders WHERE owner=? AND id=? AND json_extract(data,'$.status')=? AND EXISTS (SELECT 1 FROM removed_orders WHERE company_id=? AND order_id=?)").bind(companyId,id,'Prepared — not sent',companyId,id)
]);
const remaining=await db.prepare('SELECT id FROM orders WHERE owner=? AND id=?').bind(companyId,id).first();
if(remaining)return Response.json({error:'Only prepared, unsent orders can be removed.'},{status:409});
const removed=await db.prepare('SELECT order_id FROM removed_orders WHERE company_id=? AND order_id=?').bind(companyId,id).first();
if(!removed)return Response.json({error:'Order not found.'},{status:404});
return Response.json({removedId:id});
}if(b.action==='product'){const p=product.parse(b.product);await db.prepare('INSERT INTO products (owner,id,data) VALUES (?,?,?) ON CONFLICT(owner,id) DO UPDATE SET data=excluded.data').bind(companyId,p.id,JSON.stringify(p)).run();return Response.json({ok:true});}const data=z.object({action:z.literal('prepare'),id:z.string().uuid(),items:z.array(z.object({id:z.string(),quantity:z.number().int().min(1).max(999)})).min(1).max(100)}).parse(b);const tombstone=await db.prepare('SELECT order_id FROM removed_orders WHERE company_id=? AND order_id=?').bind(companyId,data.id).first();if(tombstone)return Response.json({error:'This prepared order was removed. Start a new order.'},{status:409});const existing=await db.prepare('SELECT data FROM orders WHERE owner=? AND id=?').bind(companyId,data.id).first<{data:string}>();if(existing)return Response.json({order:JSON.parse(existing.data)});if(new Set(data.items.map(i=>i.id)).size!==data.items.length)return Response.json({error:'Duplicate products.'},{status:400});const rows=await db.prepare('SELECT data FROM products WHERE owner=?').bind(companyId).all<{data:string}>();const catalog=rows.results.map(r=>JSON.parse(r.data) as Product);const items=data.items.map(i=>{const p=catalog.find(p=>p.id===i.id);if(!p)throw new Error('Product missing');return {...p,quantity:i.quantity};});const order={id:data.id,created:new Date().toISOString(),status:'Prepared — not sent',items,total:items.reduce((a,i)=>a+i.price*i.quantity,0)};await db.prepare('INSERT OR IGNORE INTO orders (owner,id,data,created) SELECT ?,?,?,? WHERE NOT EXISTS (SELECT 1 FROM removed_orders WHERE company_id=? AND order_id=?)').bind(companyId,order.id,JSON.stringify(order),order.created,companyId,order.id).run();const saved=await db.prepare('SELECT data FROM orders WHERE owner=? AND id=?').bind(companyId,data.id).first<{data:string}>();if(!saved)return Response.json({error:'This order was removed. Start a new order.'},{status:409});return Response.json({order:JSON.parse(saved.data)});}catch(e){console.error(e);return Response.json({error:e instanceof z.ZodError?'Check the required fields and quantities.':'Could not save. Your input is still here; please retry.'},{status:e instanceof z.ZodError?400:503});}}
